PintaProject/Pinta

- Pinta.Core/Pinta.Core.csproj
- Pinta.Effects/Pinta.Effects.csproj
- Pinta.Gui.Widgets/Pinta.Gui.Widgets.csproj
- Pinta.Tools/Pinta.Tools.csproj
- Pinta/Pinta.csproj
Without this, Mono will compile Pinta against Mono.Posix 4.0.0.0, which is not included in Mono's GTK# for Windows installer, so Mono compiled Pinta cannot run on .NET.
> Explicitly compile against Mono.Posix 2.0.0.0.

- Pinta.Core/Extensions/CairoExtensions.cs
Previously we had used g.FixedStrokeExtents with a small line width to get a bounding box around a path.  During recent testing, I was able to reproduce bug #1313773 and it was caused by g.FixedStrokeExtents() returning an empty rectangle when I attempted to crop an ellipse selection.  I believe bug #1313773 was solved by other means (I can no longer reproduce it), but I still think it would be better to use cairo_path_extents() to get the bounds of a path.
> To get bounds of path, changed from StrokeExtents to PathExtents

- Pinta.Core/Classes/DocumentWorkspace.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta.Docking/DockNotebook/DockNotebook.cs
- Pinta.Docking/DockNotebook/DockNotebookContainer.cs
- Pinta.Docking/DockNotebook/DockNotebookManager.cs
- Pinta.Docking/Pinta.Docking.csproj
- Pinta/Actions/View/ImageTabsToggledAction.cs
- Pinta/DocumentViewContent.cs
- Pinta/MainWindow.cs
Refactor all public static DockNotebook functions into a static class called DockNotebookManager, and add some convenience methods for work we had in MainWindow.
Also update behavior:
- New tabs will be added to the active container rather than the first container.
- New tabs will be added to the right of the active tab rather than the end.
> Tab code cleanup

- Pinta/Dialogs/NewImageDialog.cs
as sugested in https://bugs.launchpad.net/pinta/+bug/1424547
I moved the preview to the right, added a Label saying preview on top of it, and made it slightly bigger
Old: http://i.imgur.com/hAz2gbf.png
New: http://i.imgur.com/qcYRgFF.png
> Improved New Dialog

- Pinta.Tools/Tools/TextTool.cs
The "outline width" settings on the toolbar for the Text tool now only show up if they are relevant to the stroke style being used. I also normalized the indentation to use tabs consistently throughout the file.
> Normalized indentation in TextTool.cs and fix for ticket 1426663

- .travis.yml
However not Mono 4 as I know that will fail from https://build.opensuse.org/package/show/Mono:Community/pinta (see openSUSE:Factory).
> Updated Travis CI to build with a more recent version of Mono

- autogen.sh
Without this the script crashes and burns when you have environment variables like
GREP_OPTIONS="--binary-files=without-match --line-number"
as I do.
> Prevent grep from taking messy environment options in autogen

- Pinta.Core/Extensions/CairoExtensions.cs
therefore before converting to Gdk.Pixbuf R,G,B values must be converted.
See:
http://cairographics.org/manual/cairo-Image-Surfaces.html#cairo-format-t
Using Gdk.pixbuf_get_from_surface() (Gdk 3) would probably be a better and faster solution...
> Cairo Images have premultiplied alpha values

- Pinta.Core/Effects/UnaryPixelOps.cs
reason is that cairo images use premultiplied alpha values
> InvertColorsEffect does not work correct for alpha values != 255

- Pinta.Tools/Editable/Shapes/RoundedLineEngine.cs
Instead of the rectangle, a triangle with one point at (0,0) is drawn.
Reason is that divide by 0 error is not prevented correctly, resulting in NaN.
> Strange behaviour when width or height of a drawn rounded rectangle is 0

- Pinta.Resources/ResourceManager.cs
GetIcon() does not support loading icons if the icon is in the resource of a different assembly. This is needed to support icons in plugins.
> Support loading icons from other assemblies (e.g. Plugins)

- Pinta.Core/Classes/Document.cs
- Pinta.Core/Classes/Layer.cs
- Pinta.Core/Managers/LivePreviewManager.cs
- Pinta.Tools/Tools/MoveSelectedTool.cs
- Pinta/Actions/Layers/LayerPropertiesAction.cs
- Pinta/Dialogs/LayerPropertiesDialog.cs
- changing ctx.Operator before a call to layer.Draw(...) has no effect because the BlendMode is overwritten by layer.Draw(...).
The error can be seen e.g. when having a colored semi-transparent image and apply a black and white filter. In the regions of the image where alpha is != 255 there remain colored parts.
- Layerproperties are corretly applied if "MoveSelectionTool" is active, but not if "MoveSelectedTool" is active.
- MoveSelectedTool does not react on changes in Opacity, Visibility and BlendMode
> corrected display problems in MoveSelectedTool and LivePreviewManager

- configure.ac
Using AC_PATH_PROG isn't the standard way and breaks if
the distribution provides only prefixed (as in: <arch>-pkg-config)
versions.
> Use PKG_PROG_PKG_CONFIG macro to check for pkg-config

- readme.md
Simple correction to readme to follow CommonMark specifications [CommonMark](http://spec.commonmark.org/0.26/#atx-headings)
This might lead to the readme not being well rendered in markdown viewers, as it happened when I used vmd -- https://github.com/yoshuawuyts/vmd/issues/90
CommonMark spec:
An ATX heading consists of a string of characters, parsed as inline
content, between an opening sequence of 1–6 unescaped # characters
and an optional closing sequence of any number of unescaped #
characters. The opening sequence of # characters must be followed by
a space or by the end of line.
> Markdown correction adding spaces after heading

- Pinta.Core/Classes/BaseTool.cs
- Pinta.Core/Effects/ColorBgra.cs
- Pinta.Tools/Tools/PencilTool.cs
Enabled a drop down that allows the user to select between normal blend mode and overwrite mode.
Also adds support for overwrite to the pencil tool.
Fixes: [#1688743](https://bugs.launchpad.net/pinta/+bug/1688743)
> Enable alpha blending toolbar drop down for pencil tool

- Pinta.Tools/Brushes/PlainBrush.cs
I found one other place where a call to SetColorBgra was made without using a premultiplied alpha and I verified that passing the result of ToPremultipliedAlpha to CairoExtensions.SetColorBgra does give the same result as the LineTo call without antialiasing.
I had to make a similar correct in this pull request: https://github.com/PintaProject/Pinta/pull/124
> Fix PlainBrush to use premultiplied alpha for single pixel strokes

- Pinta.Core/Actions/EditActions.cs
- Pinta.Core/Classes/Palette.cs
- Pinta.Core/Managers/SettingsManager.cs
- Pinta.Core/Managers/SystemManager.cs
- Pinta.Core/PaletteFormats/GimpPalette.cs
- Pinta.Core/PaletteFormats/IPaletteLoader.cs
- Pinta.Core/PaletteFormats/IPaletteSaver.cs
- Pinta.Core/PaletteFormats/PaintDotNetPalette.cs
- Pinta.Core/PaletteFormats/PaintShopProPalette.cs
- Pinta.Core/PaletteFormats/PaletteDescriptor.cs
- Pinta.Core/PaletteFormats/PaletteFormats.cs
- Pinta.Core/Pinta.Core.csproj
[PaintShopPro.pal](https://raw.githubusercontent.com/Mailaender/ArtSrc/f3e8d2f33a34e1ce3258b3b8dd21543acd72a2d4/ra/palettes/PaintShopPro.pal) can be used as a test file.
I also made it easier for future palette file format additions and maybe even do this in addin form.
> Added support for JASC PaintShop Pro palette files

- po/es.po
The current had an illegal character (0xC2) that breaks zooming, so that it just doesnt' work (neither Ctrl++ nor the buttons) when "es" is the current locale. See for example: https://bugs.launchpad.net/pinta/+bug/1464855
This fixes that by turning it into a space, that probably was what the translator meant.
> Update es.po - text breaks functionality

- Pinta.Core/Classes/DocumentWorkspace.cs
To see the problem, zoom in to 1600% and then try to draw a 1 pixel wide line with the line/curve tool with anti-aliasing off.
Without this fix the line will often start and end on a different pixel than the one you click.
> Fix a rounding problem causing the wrong pixel to be clicked on when drawing lines when zoomed in

- readme.md
Else you can have an error like this after running autogen :
```
checking for mono... /usr/bin/mono
checking for MONO... yes
./configure: line 3567: syntax error near unexpected token `0.35.0,'
./configure: line 3567: `AC_PROG_INTLTOOL(0.35.0, no-xml)'
```
> added pkg required to build

- osx/pinta
I've updated DOWNLOAD_URL to point to the current stable download page for Mono. The go-mono URL returns a 404.
> Update OSX Mono download URL

- Pinta.Core/Actions/ViewActions.cs
I'm not really sure why this is happening, but on linux (arch linux updotade version January 2019) I need to remove trailing whitespace in order to parse zoom level
```
$ mono --version
Mono JIT compiler version 5.16.0 (makepkg/bb3ae37d71a Sat Dec  8 13:21:35 CET 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
TLS:           __thread
SIGSEGV:       altstack
Notifications: epoll
Architecture:  amd64
Disabled:      none
Misc:          softdebug 
Interpreter:   yes
LLVM:          supported, not enabled.
GC:            sgen (concurrent by default)
```
Anyway this a a change that cannot cause any harm, so please consider to apply.
NOTE: Didn't see any report of this, so maybe this is only my machine, or this is stopping people to use pinta.
> Fix parsing zoom level

- Pinta.Install.proj
- xdg/pinta.appdata.xml.in
- xdg/pinta.desktop.in
Desktop file:
- Add `Version` entry
- Add `TryExec` entry
- Add `StartupWMClass` entry
- Add `Keywords` entry
AppData file:
- Move `categories` and `keywords` to desktop file
- Remove `UserDocs` from `kudos` because documentation is not bundled
Pinta.Install.proj:
- Install AppData file
> Update XDG files

- Pinta.Tools/Tools/BaseTransformTool.cs
- Pinta.Tools/Tools/MoveSelectedTool.cs
- Pinta.Tools/Tools/MoveSelectionTool.cs
Resizing the actual contents of a selection is something I noticed right away that was missing when compared to Paint.NET. This PR introduces behavior that doesn't mirror Paint.NET's resize handles directly, but it at least provides a way to resize the contents of the current selection without copying your selection in to a temporary file and resizing the whole canvas.
> Hold control to resize selection when you're in the move-selected tool

- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
Here's a feature I found myself missing on Pinta after using Paint.NET for so long: horizontal scrolling of the image canvas with the mouse wheel while `Shift` is held down!
So I decided to implement it (after cleaning up the source file) :)
> PintaCanvas: Implement horizontal scrolling using Shift-MouseWheel

- Pinta.Core/Managers/PaletteManager.cs
- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
- Pinta.Gui.Widgets/Widgets/ColorPaletteWidget.cs
In Paint.net one can switch between primary and secondary color with the shortcut key **X**. When using Pinta, I'm really missing that shortcut, so I added it in!
> Add shortcut key for switching palette color

- .github/workflows/build.yml
- Pinta.Core/Pinta.Core.csproj
- Pinta.Docking/Pinta.Docking.csproj
- Pinta.Effects/Pinta.Effects.csproj
- Pinta.Gui.Widgets/Pinta.Gui.Widgets.csproj
- Pinta.Resources/Pinta.Resources.csproj
- Pinta.Tools/Pinta.Tools.csproj
- Pinta/Pinta.csproj
- tests/Pinta.Core.Tests/Pinta.Core.Tests.csproj
Given that .NET 5.0 is stable now and contains many performance improvements, we will probably want the eventual release to target it.
Also adds a Windows CI build.
> Target net5.0.

- Pinta.Core/Managers/ImageConverterManager.cs
- Pinta.Core/Managers/PaletteManager.cs
- Pinta.Core/Managers/SettingsManager.cs
- Pinta.Core/PintaCore.cs
- Pinta/Actions/File/NewDocumentAction.cs
- Pinta/Actions/File/NewScreenshotAction.cs
- Pinta/MainWindow.cs
When saving the user's recently used colors, a circular dependency was created between `SettingsManager` and `PaletteManager`.  This can be fixed by removing palette loading/saving code from `SettingsManager` and putting it in `PaletteManager` which seems more appropriate.
A few other changes:
- Make `SaveSettings ()` private.  There's not much reason to make the user wait while we write to disk every time a setting changes, instead we will write all settings to disk when the user exits the application.
- Calling code is free to use `PutSetting ()` any time they want and it will be written to disk on exit
- -or- Code can subscribe to the new `SettingsManager.SaveSettingsBeforeQuit` event and will be given a chance to add their setting(s) when the app is exiting.
- Rewrote code in …
> Rework SettingsManager.

- Pinta.Tools/Tools/TextTool.cs
#158 changed `TextTool.CurrentTextEngine` to throw an exception rather than return `null` when there is not an `ActiveDocument`.  However there is a place where it is checked for `null` to avoid performing action if there is no ActiveDocument. 
Thus if you click the Text Tool while there is no document open, it throws an exception.  This guards against that by checking if there are any open documents instead of checking if `CurrentTextEngine` is `null`.
> Fix exception in TextTool caused by NRT changes.

- Pinta.Core/Extensions/ObsoleteExtensions.cs
- Pinta.Core/Managers/EffectsManager.cs
- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
- Pinta.Gui.Widgets/Widgets/Canvas/CanvasWindow.cs
- Pinta.Gui.Widgets/Widgets/ColorGradientWidget.cs
- Pinta.Gui.Widgets/Widgets/Ruler.cs
- Pinta/Options.cs
Not sure if this is desired or not, but it moves the remaining `[Obsolete]` GTK usage we have into an `ObsoleteExtensions` class and ignores the obsolete warnings from there.
This makes the build warning-free, which should help make it easier to ensure no new warnings are committed, as they won't be drowned out by obsolete warnings.
> Move remaining GTK obsolete API calls to ObsoleteExtensions.

- Pinta.Core/Classes/DocumentHistory.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta/Actions/Edit/PasteIntoNewImageAction.cs
Today `Paste Into New Image` is implemented as: create new document, activate the paste action, activate the deselect action.  This leaves the user starting with the following history items:
* New Image
* Paste
* Finish Pixels
* Deselect
This doesn't really feel like what the user asked for, as well as several of the history items maintain an `old_surface` which takes up unneeded memory.
Instead, this creates a new document and then copies the clipboard image to the document surface.  The only history item is `New Image`, which seems more like what the user would expect.  The only tricky part is we need to mark the document as dirty, since we should prompt the user to save the pasted image, even if they make no changes to it.
> Implement Paste Into New Image without extra history items.

- Pinta.Core/Effects/ColorBgra.cs
- Pinta.Core/Managers/PaletteManager.cs
- Pinta.Gui.Widgets/Widgets/StatusBarColorPaletteWidget.cs
Persists the Primary/Secondary colors in settings between application starts.
Also makes it so clicking the "swap colors" icon does not alter the most recently used colors palette.
> Store Primary/Secondary colors in settings.

- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
- Pinta.Gui.Widgets/DialogAttributes.cs
- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
- Pinta.Gui.Widgets/Widgets/AnglePickerGraphic.cs
- Pinta.Gui.Widgets/Widgets/AnglePickerWidget.cs
- Pinta.Gui.Widgets/Widgets/Canvas/CanvasRenderer.cs
- Pinta.Gui.Widgets/Widgets/Canvas/CanvasWindow.cs
- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
- Pinta.Gui.Widgets/Widgets/ColorGradientWidget.cs
- Pinta.Gui.Widgets/Widgets/ColorPanelWidget.cs
- Pinta.Gui.Widgets/Widgets/ComboBoxWidget.cs
- Pinta.Gui.Widgets/Widgets/FilledAreaBin.cs
- Pinta.Gui.Widgets/Widgets/HScaleSpinButtonWidget.cs
- Pinta.Gui.Widgets/Widgets/HistogramWidget.cs
- Pinta.Gui.Widgets/Widgets/History/HistoryTreeView.cs
- Pinta.Gui.Widgets/Widgets/PointPickerGraphic.cs
- Pinta.Gui.Widgets/Widgets/PointPickerWidget.cs
- Pinta.Gui.Widgets/Widgets/ReseedButtonWidget.cs
- Pinta.Gui.Widgets/Widgets/Ruler.cs
Tidy up `Pinta.Gui.Widgets`:
- Format code to fit `.editorconfig`
- Use modern C# like `var`, auto-properties, pattern matching, object initialization syntax, etc.
- Refactor to handle NRT correctly without needing the null-forgiveness operator.
This PR does not contain any functional changes.
> Tidy up Pinta.Gui.Widgets.

- Pinta.Core/Classes/BaseTool.cs
- Pinta.Core/Extensions/ToolBoxButton.cs
- Pinta.Core/HistoryItems/FinishPixelsHistoryItem.cs
- Pinta.Core/HistoryItems/PasteHistoryItem.cs
- Pinta.Core/Managers/ToolManager.cs
- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
- Pinta.Tools/Tools/ColorPickerTool.cs
- Pinta/Actions/Edit/PasteAction.cs
- Pinta/MainWindow.cs
Today, `BaseTool.Name` is localized.  This can cause issues when we try to set or retrieve a tool based on its name, as we have to specify the localized name. There is a case where we do not do this, which likely does not work on certain locales:
- https://github.com/PintaProject/Pinta/blob/gtk3-v2/Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs#L154
While we could (maybe?) fix this call, it seems like a bad design that might bite us again in the future.
Instead of operating on localized tool names, change `ToolManager.SetCurrentTool (string)` to work on type names, as they are not localized.
> Make ToolsManager.SetCurrentTool (string) take a type name.

- Pinta.Gui.Widgets/Widgets/Canvas/CanvasWindow.cs
- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
Handling Ctrl-MouseWheel for zoom on `PintaCanvas` doesn't seem to work in GTK3.  The event is fired on the `Viewport` instead.  This PR fixes Ctrl-MouseWheel zooming.
Additionally, Shift-MouseWheel horizontal scrolling seems to be built into GTK3 (?), as it still functions as expected with this code removed.  (The code is never fired in the existing codebase.)
> Fix zooming with Ctrl-MouseWheel.

- installer/linux/pinta.in
Use system default `dotnet` executable (in `$PATH`). This allows building with a SDK installed in a different path then the runtime. This is especially helpful for packaging.
> Use system default dotnet to start Pinta on Linux.

- xdg/Makefile.am
/usr/share/appdata/ is the legacy path. See: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location
> Install appdata into /usr/share/metainfo/ directory

- Pinta.Core/Actions/FileActions.cs
- Pinta.Core/Classes/Document.cs
- Pinta.Docking/MonoDevelop.Ide.Gui/IViewContent.cs
- Pinta.Docking/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
- Pinta/Actions/File/SaveDocumentImplementationAction.cs
- Pinta/DocumentViewContent.cs
Currently, tooltips on the opened tabs only display its filename, which isn't very helpful if there are multiple tabs open with the same filename. This PR changes the tooltip behavior to display the full path of that file to help differentiate between each tab.
I also added the display of full-path tooltips for the list of files under 'File > Recently opened..'. Fortunately, GTK has the logic covered and just needed to flip a boolean value.
> Show full file paths as tooltips for opened tabs and for 'recently opened' files

- Pinta.Core/Extensions/CairoExtensions.cs
Fixes the corner missing when using the rectangle shape tool with an outline. https://bugs.launchpad.net/pinta/+bug/1922470
Since this bug was marked as a 1.8 milestone, I wasn't sure if it should be added to the gtk 3 branch or master branch. I've attached a before and after picture.
> Fix missing rectangle shape corner

- Pinta.Tools/Tools/TextTool.cs
This fixes the text background appearing outside of the selection box as reported here. https://bugs.launchpad.net/pinta/+bug/1910511
However, the bug report also mentions that the text tool can click outside of the selection area and that this is a bug. I tested how Paint.net handles this and it's the same. You are allowed to click outside of a selection box. Considering that other tools, like the paint brush and shape tools also let you click outside the selection box, it appears this is intended behavior. I think it would be best to have the user resubmit it as an idea/wishlist if they want it changed.
Also, I don't have any experience with C# or Cairo, so my solution might not be good. From what I was able to figure out, the text background used a separate Cairo context and it wasn't …
> Fix text background outside of selection

- Pinta.Core/Actions/LayerActions.cs
Fix bug https://bugs.launchpad.net/pinta/+bug/1909578 by adding Move Layer Down/Up actions to the Gtk.Application.  These appear to have been left out because they aren't part of the main menu, only the Layer pad toolbar.
> [Bug 1909578] Add Move Layer Down/Up actions to Gtk.Application so they function.

- Pinta/DocumentViewContent.cs
Fixes https://bugs.launchpad.net/pinta/+bug/1909754
It appears that the GTK Notebook does not have native support for a "dirty" state like the MonoDevelop docking library we previously used did.  We'll have to revert to the tried and true asterisk to denote a tab is dirty.
> [Bug 1909754] Use asterisk on image tab to denote image has not been saved.

- Pinta.Core/Classes/DocumentHistory.cs
Fixes https://bugs.launchpad.net/pinta/+bug/1909577.
The history stack works on the assumption that the initial history item (`New Image` or `Open Image`) cannot be "undone".  In some cleanup the `CanUndo` function began checking `Pointer >= 0` instead of `Pointer > 0`.
Original code:
https://github.com/PintaProject/Pinta/blob/master/Pinta.Core/Classes/DocumentWorkspaceHistory.cs#L116-L119
> [Bug 1909577] Do not let New/Open Image history be undone.

- Pinta.Tools/Editable/EditEngines/ArrowedEditEngine.cs
Fixes: https://bugs.launchpad.net/pinta/+bug/1910493
Rework the toolbar building for `ArrowedEditEngine` to ensure that the arrow options toolbar items are always shown properly, persisting across:
- Pinta restarts
- Tool item changes
- Tab changes
> [Bug 1910493] Ensure arrow options toolbar is correctly built on Pinta launch.

- Pinta.Tools/Tools/TextTool.cs
Update of backup value after font change, fix of [#1910495](https://bugs.launchpad.net/pinta/+bug/1910495).
> Bugfix of text font changes (#1910495).

- Pinta.Core/Actions/ViewActions.cs
The current View menu feels like the various "show/hide window chrome" menu items crowd out the likely more used items like zoom.
Place these likely less frequently used menu options in a submenu:
> Put rarely used View menu items into a submenu.

- Pinta.Core/Managers/LivePreviewManager.cs
If you use an effect with Live Preview and select "Apply", the `live_preview_surface` is set to `null` without being `Dispose ()`'d first.
> Fix case in live preview where Surface is not disposed.

- Directory.Build.props
- Makefile.am
- Pinta.Core/Pinta.Core.csproj
- Pinta.Docking/Pinta.Docking.csproj
- Pinta.Effects/Pinta.Effects.csproj
- Pinta.Gui.Widgets/Pinta.Gui.Widgets.csproj
- Pinta.Resources/Pinta.Resources.csproj
- Pinta.Tools/Pinta.Tools.csproj
- Pinta/Pinta.csproj
- tests/Pinta.Core.Tests/Pinta.Core.Tests.csproj
Anything put in the magically-named `Directory.Build.props` file will be automatically pulled in to any `.csproj` files in a tree.  By moving `<Version>` there, it only needs to be updated in one place instead of X places.
Additionally remove `<RootNamespace>` and `<AssemblyName>`.  These values are defaulted to the `.csproj` name, so specifying them is redundant in an SDK-style `.csproj` world.
> Use Directory.Build.props to simplify version management.

- Pinta.Core/Classes/Translations.cs
- Pinta.Gui.Widgets/Widgets/Canvas/CanvasRenderer.cs
- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
- Pinta.Gui.Widgets/Widgets/Layers/LayersListWidget.cs
- Pinta.sln
- tests/PintaBenchmarks/AdjustmentsBenchmarks.cs
- tests/PintaBenchmarks/CanvasRendererBenchmarks.cs
- tests/PintaBenchmarks/EffectsBenchmarks.cs
- tests/PintaBenchmarks/PintaBenchmarks.csproj
- tests/PintaBenchmarks/Program.cs
- tests/PintaBenchmarks/Utilities/MillisecondConfig.cs
- tests/PintaBenchmarks/Utilities/TestData.cs
Add a benchmark test suite based on `BenchmarkDotNet` to help inform future performance work.  Made a few modifications to ensure that performance sensitive classes we are profiling do not attempt to use `PintaCore`, which fails to initialize because we are not running in the full Pinta context.
Example data:
|             Method |       Mean |     Error |     StdDev | Allocated |
|------------------- |-----------:|----------:|-----------:|----------:|
|     RenderOneToOne |   2.237 ms | 0.0264 ms |  0.0247 ms |     242 B |
| RenderManyOneToOne |  10.498 ms | 0.1357 ms |  0.1133 ms |     824 B |
|       RenderZoomIn |  40.482 ms | 0.7919 ms |  1.2094 ms |  28,384 B |
|   RenderManyZoomIn | 392.806 ms | 7.7580 ms | 20.7075 ms |  29,600 B |
|      RenderZoomOut |   8.614 ms | 0.1719 ms | …
> Add benchmark test suite.

- Pinta.Core/Classes/ScaleFactor.cs
- Pinta.Gui.Widgets/Widgets/Canvas/CanvasRenderer.cs
Caching a few values and a scratch surface can give us some nice wins, particularly for rendering a zoomed in canvas.
|             Method |       Mean |     Error |    StdDev | Allocated |
|------------------- |-----------:|----------:|----------:|----------:|
|     RenderOneToOne |   2.159 ms | 0.0388 ms | 0.0363 ms |     242 B |
| RenderManyOneToOne |   9.597 ms | 0.1060 ms | 0.0940 ms |     824 B |
|       RenderZoomIn |  42.322 ms | 0.2513 ms | 0.2350 ms |  29,294 B |
|   RenderManyZoomIn | 404.774 ms | 3.2200 ms | 3.0120 ms |  29,600 B |
|      RenderZoomOut |   8.205 ms | 0.1055 ms | 0.0987 ms |     272 B |
|  RenderManyZoomOut |  76.499 ms | 0.7711 ms | 0.7213 ms |   1,574 B |
|             Method |       Mean |     Error |    StdDev | Allocated |
|------------------- …
> Cache a few things to speed up canvas rendering.

- CHANGELOG.md
- Pinta.Gui.Widgets/Widgets/Canvas/CanvasRenderer.cs
This still needs some more testing, but has some good performance improvements in the benchmarks
|             Method |       Mean |     Error |     StdDev | Allocated |
|------------------- |-----------:|----------:|-----------:|----------:|
|     RenderOneToOne |   4.322 ms | 0.0942 ms |  0.2734 ms |     254 B |
| RenderManyOneToOne |  23.601 ms | 0.6252 ms |  1.8237 ms |     850 B |
|       RenderZoomIn |  38.219 ms | 0.7541 ms |  1.8640 ms |  28,399 B |
|   RenderManyZoomIn | 231.494 ms | 5.5985 ms | 16.3310 ms |  29,184 B |
|      RenderZoomOut |  11.879 ms | 0.2343 ms |  0.3434 ms |     288 B |
|  RenderManyZoomOut | 108.522 ms | 2.2333 ms |  6.4079 ms |   1,011 B |
|             Method |       Mean |     Error |    StdDev | Allocated |
|------------------- …
> Perform the zoom in/out canvas rendering with Cairo

- Pinta.Gui.Widgets/Widgets/Ruler.cs
Do you know what the intent behind these Gravity flags is?  Using one of them is fine, but when using both of them it causes the values to be written as squares.  (Win10)
This PR fixes this by removing the flags and moving the text into place, but it may not be the correct fix. 🤷‍♂️
> Fix Ruler rendering issue.

- Pinta.Resources/Icons.cs
- Pinta.Resources/icons/hicolor/scalable/actions/tool-move-cursor-symbolic.svg
- Pinta.Tools/Tools/MoveSelectedTool.cs
This PR fixes that the "Move Selected Pixels" tool had a cursor that was not visible on a dark background. 
In #204 amazing icons where added, however the new cursor for the tool "Move Selected Items" (Pinta.Resources/icons/hicolor/scalable/actions/tool-move-symbolic.svg) only contains the color black. This means it is not visible against a dark background.
This PR fixes that by adding a white stroke to the svg. 
A new file has been made specifically for the cursor because otherwise the toolbar icon wouldn't look nice.
<sub>The new cursor up close</sub>
https://user-images.githubusercontent.com/23642000/150661125-dff1fa47-2282-4dd4-88fa-809e8acffab8.mp4
> Added new cursor icon for tool move selected

- Pinta.Core/Actions/EditActions.cs
- Pinta.Core/Actions/LayerActions.cs
- Pinta.Core/Actions/WindowActions.cs
- Pinta.Core/Classes/Document.cs
- Pinta.Core/Classes/Palette.cs
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Core/Extensions/GtkExtensions.cs
- Pinta.Core/ImageFormats/GdkPixbufFormat.cs
- Pinta.Core/ImageFormats/IImageExporter.cs
- Pinta.Core/ImageFormats/IImageImporter.cs
- Pinta.Core/ImageFormats/JpegFormat.cs
- Pinta.Core/ImageFormats/OraFormat.cs
- Pinta.Core/ImageFormats/TgaExporter.cs
- Pinta.Core/Managers/PaletteManager.cs
- Pinta.Core/Managers/SystemManager.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta.Core/PaletteFormats/GimpPalette.cs
- Pinta.Core/PaletteFormats/IPaletteLoader.cs
- Pinta.Core/PaletteFormats/IPaletteSaver.cs
- Pinta.Core/PaletteFormats/PaintDotNetPalette.cs
- Pinta.Core/PaletteFormats/PaintShopProPalette.cs
- Pinta/Actions/File/CloseDocumentAction.cs
- Pinta/Actions/File/OpenDocumentAction.cs
- Pinta/Actions/File/SaveDocumentImplementationAction.cs
- Pinta/DocumentViewContent.cs
- Pinta/Main.cs
- Pinta/MainWindow.cs
This is very much a work in progress so far..
Using [GFile](https://docs.gtk.org/gio/iface.File.html) allows us to better support virtual filesystems - e.g. for [bug 1958763](https://bugs.launchpad.net/pinta/+bug/1958763), we can show the real filename (like `test.png`) for a file loaded from the Gnome Google Drive mount, rather than a unique identifier that isn't user-friendly
In GTK4, the [file chooser](https://docs.gtk.org/gtk4/iface.FileChooser.html) will also only provide us with a [GFile](https://docs.gtk.org/gio/iface.File.html) so this also helps us prepare a bit for GTK4 
TODO
> Use GFile for file manipulation 

- Pinta.Core/Actions/EditActions.cs
- Pinta.Core/Actions/LayerActions.cs
- Pinta.Core/ImageFormats/FormatDescriptor.cs
- Pinta.Core/Managers/ImageConverterManager.cs
- Pinta/Actions/File/OpenDocumentAction.cs
Tested on Ubuntu 20.04
Pinta currently sets the filter for files in the file chooser dialogs based entirely on filenames. Instead, it is preferable to base this filter based on MIME types. This means that on Linux systems for example, there is no need to specify a file extension to be recognised as an image file. The identification of the file is left to the system, which can use more advanced heuristics, primarily, identifying the type based on the files binary header / magic number.
The observed effect is is that when filtering for images, Pinta will be capable of identifying image files without a file extension, whilst excluding other types of files, e.g ODT documents, that would be found with "All Files" filter.
It isn't strictly necessary to remove the file extensions filtering, the …
> Use MIME filters for file dialogs on non-Windows systems 

- Pinta.Core/Classes/Re-editable/Text/TextEngine.cs
https://bugs.launchpad.net/pinta/+bug/1964398
When Ctrl+x is pressed with the text tool active, with empty text or some text entered(without finalizing) and without selecting the text, an exception is raised by the app.
This commit fixes that issue by adding a `hasSelection()` prior to calling `DeleteSelection()`. Works fine as far as I tested.
> Fix for #1964398: Added hasSelection check in PerformCut()

- patch-guidelines.md
The headers were not being displayed as headers by GitHub. This is because GitHub requires that the hash symbols are followed by a space character to recognize text as a header.
> Fix formating for headers in patch-guidelines.md

- Pinta.Core/Classes/Re-editable/Text/TextEngine.cs
- Pinta.Core/Classes/ScaleFactor.cs
- Pinta.Core/Effects/BinaryPixelOp.cs
- Pinta.Core/Effects/ColorBgra.cs
- Pinta.Core/Effects/Histogram.cs
- Pinta.Core/Effects/HsvColor.cs
- Pinta.Core/Effects/PixelOp.cs
- Pinta.Core/Effects/RgbColor.cs
- Pinta.Core/Effects/UnaryPixelOp.cs
- Pinta.Core/Effects/UnaryPixelOps.cs
- Pinta.Core/Effects/Utility.cs
- Pinta.Core/Extensions/GioStream.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta.Gui.Widgets/Widgets/ColorGradientWidget.cs
- Pinta.Tools/Tools/SelectTool.cs
- Pinta/Options.cs
I am thinking of doing a major modernization (and later a refactoring) of the Pinta codebase, but splitting it into very safe, bite-sized pieces. This is one of them. And very few things are safer and more bite-sized than using the `nameof()` operator for exceptions :)
On a related note, in a previous pull request I was asked not to change certain file too much because it was third-party code. I saw that the file in question was licensed to Novell, so I assume that is what was being talked about. Is my guess correct? What is the policy on third-party code? It's probably important to note that the file in question is under a permissive, MIT-like license.
> Changed occurrences of ArgumentOutOfRangeException and ArgumentException to use nameof() operator

- tests/Pinta.Core.Tests/OtherExtensionsTest.cs
In a previous pull request, I added an extension method called `ToReadOnlyCollection`. One of the claims in the documentation comments is "[...] it creates a wrapped read-only copy of the values generated by the `IEnumerable<T>` argument [...] except if [...] the argument is an object that has been previously returned from this method, in which case the reference is returned as is."
Let's put that claim to the test
> Added simple test to `OtherExtensions.ToReadOnlyCollection`

- Pinta.Core/Effects/GradientRenderers.cs
For now I'm fixing them as I find them, as I haven't found a way to find all of them solution-wide
> Fixed naming violations in `GradientRenderers.cs`

- Pinta.Core/PaletteFormats/PaletteDescriptor.cs
There are more places in the code where an array is exposed publicly, but for now I'm only doing this file, so that conflicts with other open pull requests are avoided
> `PaletteDescriptor.Extensions` was turned into `ReadOnlyCollection<T>`

- Pinta.Core/Effects/BitMask.cs
- tests/Pinta.Core.Tests/BitMaskTest.cs
They don't cover all of its features yet, but it's a good start.
One of my goals is to be able to safely refactor algorithm code in the future (the tests would give us some peace of mind that the refactoring is functionally equivalent to the original). The specific algorithm that I want to refactor uses `BitMask`, so I'm adding tests to it first.
Also, I sealed the `BitMask` class and added argument checks.
> Added basic tests for `BitMask`

- Pinta.Core/PaletteFormats/PaintDotNetPalette.cs
The order of execution of `Dispose()` when a `using` is used is from innermost to outermost, so it should be fine
> Refactored away try/finally block in `PaintDotNetPalette`

- Pinta.Core/EventArgs/BrushEventArgs.cs
- Pinta.Core/EventArgs/CanvasInvalidatedEventArgs.cs
- Pinta.Core/EventArgs/DocumentCancelEventArgs.cs
- Pinta.Core/EventArgs/DocumentEventArgs.cs
- Pinta.Core/EventArgs/HistoryItemAddedEventArgs.cs
- Pinta.Core/EventArgs/LivePreviewEndedEventArgs.cs
- Pinta.Core/EventArgs/LivePreviewRenderUpdatedEventArgs.cs
- Pinta.Core/EventArgs/LivePreviewStartedEventArgs.cs
- Pinta.Core/EventArgs/TextChangedEventArgs.cs
- Pinta.Core/EventArgs/ToolEventArgs.cs
Some setters were actually being used, so I left them
> `EventArgs` classes in `Pinta.Core` were sealed, and unused setters removed

- Pinta.Core/Classes/Point.cs
- Pinta.Core/Classes/Re-editable/Text/TextPosition.cs
- Pinta.Core/Classes/Rectangle.cs
- Pinta.Core/Classes/ScaleFactor.cs
- Pinta.Core/Effects/ColorBgra.cs
- Pinta.Core/Effects/HsvColor.cs
- Pinta.Core/Effects/RgbColor.cs
- Pinta.Core/Effects/Scanline.cs
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Core/Extensions/PangoExtensions.cs
- Pinta.Core/ImageFormats/TgaExporter.cs
- Pinta/MacInterop/Carbon.cs
This reassures us that the instance won't be modified by using them(at least at a shallow level)
> Getters and methods that only access `readonly` members were made `readonly`

- Pinta.Core/Classes/DocumentSelection.cs
- Pinta.Core/Extensions/OtherExtensions.cs
- Pinta.Tools/Tools/FloodTool.cs
- Pinta.Tools/Tools/MagicWandTool.cs
- tests/Pinta.Core.Tests/OtherExtensionsTest.cs
There's still a ways to go, but this is the first test.
Also, changed return type of it from `PointI[][]` to `IReadOnlyList<IReadOnlyList<PointI>>`, which already helps us avoid one heap allocation (by removing one `.ToArray()` call), with more optimizations to come, little by little, as the test coverage is expanded and refactorings are made :)
> Created a test for `OtherExtensions.CreatePolygonSet` with an empty stencil

- Pinta.Docking/DockNotebook.cs
- Pinta.Tools/Brushes/CircleBrush.cs
- Pinta.Tools/Brushes/GridBrush.cs
- Pinta.Tools/Brushes/PlainBrush.cs
- Pinta.Tools/Brushes/SplatterBrush.cs
- Pinta.Tools/Brushes/SquaresBrush.cs
- Pinta.Tools/Editable/EditEngines/EllipseEditEngine.cs
- Pinta.Tools/Editable/EditEngines/LineCurveEditEngine.cs
- Pinta.Tools/Editable/EditEngines/RectangleEditEngine.cs
- Pinta.Tools/Editable/EditEngines/RoundedLineEditEngine.cs
- Pinta.Tools/Tools/CloneStampTool.cs
- Pinta.Tools/Tools/SelectTool.cs
- Pinta.Tools/Tools/ShapeTool.cs
- Pinta.Tools/Tools/TextTool.cs
Done automatically by IDE + a subsequent search/replace to fix any potential issues with line endings.
Only these two projects in this pull request, though, as reviewing all occurrences in the solution at once could be too daunting.
I think this only covers the properties that have _only_ a getter.
> Modernized getter syntax in `Pinta.Docking` and `Pinta.Tools`

- Pinta.Core/Classes/DocumentLayers.cs
- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
Thanks to `yield return`.
The method is essentially a query, so it can be made lazy, (except when we need it to be eager as in the case of `PintaCanvas.Draw`, where a call to `.ToList()` was added.
> Return type of `DocumentLayers.GetLayersToPaint` is now `IEnumerable<Layer>` (instead of `List<Layer>`)

- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
- Fixed naming violation of a field
- Simplified null checking in setter through use of throw expression
- Replaced `if` block with `?.` operator
- Property change notification now uses `nameof()`
> Minor modifications of `Effects.LevelsDialog.cs`

- Pinta/DialogHandlers.cs
A programmer may think that the field can be removed, but in reality it needs to stay there to prevent its items from being garbage-collected (as discussed in #301)
> Added suppression to `DialogHandlers`

- Pinta.Resources/Icons.cs
- Pinta.Resources/ResourceManager.cs
From what I understand in #310, all switches to file-scoped namespaces are fine, so long as they happen in their own commit and the line numbers are not changed (even if an indentation level is decreased)
> File-scoped namespaces for code files in `Pinta.Resources`

- Pinta.Core/Classes/Rectangle.cs
- Pinta.Core/Classes/ScaleFactor.cs
This is a chain reaction from a previous commit (specifically #290).
Making methods `readonly` made it possible for yet more methods to become `readonly`, which I only realized until now.
> Made more methods `readonly`

- Pinta.Core/Classes/DocumentHistory.cs
- Pinta.Core/Classes/DocumentWorkspace.cs
- Pinta.Core/Classes/SurfaceDiff.cs
- Pinta.Core/Extensions/GtkExtensions.cs
- Pinta.Core/Managers/EffectsManager.cs
- Pinta.Core/Managers/LivePreviewManager.cs
- Pinta/AddinSetupService.cs
It still compiles and there is no way for users of the library to inherit from them even if they are `public`
> Sealed some classes that only have `private` or `internal` constructors

- Pinta.Tools/Editable/Shapes/EllipseEngine.cs
This is an inexpensive improvement. It doesn't result in heap allocations, so it's still efficient.
I hope to decompose the `GeneratePoints` method further in a future pull request. In my opinion it's longer than it should be.
> Extracted method `IsPerfectRectangle` in `EllipseEngine`

- Pinta.Tools/Editable/Shapes/ShapeEngineCollection.cs
For now, this was mostly done in order to understand and limit the places where their values are being modified.
The accessibility of `set`ters was limited as much as possible (with the code still compiling, of course).
For some of them, it meant removing the `set`ter entirely, and for others it was made `private`, `protected`, or `internal`.
I hope this aids future refactoring.
> Publicly exposed fields in `ShapeEngine` were turned into properties

- Pinta.Gui.Widgets/Widgets/Canvas/CanvasRenderer.cs
I wanted to use `Lazy` too, which would allow us to get rid of the nullability, but that would make the changes harder to understand, so I'm leaving it like this for now
> Lookups in `CanvasRenderer` were turned from `int[]` to `ImmutableArray<int>`

- Pinta/Actions/Addins/AddinManagerAction.cs
- Pinta/Actions/Edit/PasteIntoNewImageAction.cs
- Pinta/Actions/Edit/PasteIntoNewLayerAction.cs
- Pinta/Actions/Edit/ResizePaletteAction.cs
- Pinta/Actions/File/ExitAction.cs
- Pinta/Actions/File/ModifyCompressionAction.cs
- Pinta/Actions/File/SaveDocumentAction.cs
- Pinta/Actions/File/SaveDocumentAsAction.cs
- Pinta/Actions/Image/ResizeCanvasAction.cs
- Pinta/Actions/Image/ResizeImageAction.cs
- Pinta/Actions/View/ImageTabsToggledAction.cs
- Pinta/Actions/View/StatusBarToggledAction.cs
- Pinta/Actions/View/ToolBarToggledAction.cs
- Pinta/Actions/View/ToolBoxToggledAction.cs
- Pinta/Actions/Window/CloseAllDocumentsAction.cs
- Pinta/Actions/Window/SaveAllDocumentsAction.cs
Not for all of them, just for the short files with more or less obvious implementations.
In order to apply this I would need to know if all switches to file-scoped namespaces are fine, so long as they happen in their own commit and the line numbers are not changed (even if an indentation level is decreased). I would like to know if I understood correctly what was discussed in #310
> File-scoped namespaces for some pinta actions

- Pinta.Tools/Tools/MoveSelectedTool.cs
⚠️➡️ I actually opened this to briefly discuss a behavior of the move tool.
When using the application, a history item is created by merely _clicking_ on the canvas when the move tool is selected, even if the cursor did not move.
My question would be if this behavior is intended or if it's accidental (there was no time to get it right).
I would like to change it so that the history item is only created if the cursor actually moved.
> Introduced local variable to help make statement shorter

- Pinta.Core/Extensions/OtherExtensions.cs
It was being `Clear`ed`()` in each cycle of the `while` loop, which is one more thing that we were required to keep in mind as we read it.
If no values from the previous iteration will be used, we may as well create a new `List<PointI>` each time and let the previous one be garbage-collected.
> Reduced scope of `List<PointI>` variable being used in `OtherExtensions.CreatePolygonSet`

- Pinta.Gui.Widgets/Widgets/Canvas/CanvasRenderer.cs
In #321 I somehow forgot that `initialCapacity` is not the same as `Count`
> Correct usage of `ImmutableArray.Builder`

- Pinta.Core/Effects/UnaryPixelOps.cs
- Pinta.Effects/Adjustments/PosterizeEffect.cs
Also, for local calculations in `CalcLevels` method, an array creation was replaced by a `stackalloc`. As far as I can see, the maximum number of values on the stack is limited by a spinbox control whose value never exceeds 64, so it should be fine to allocate on the stack
> Members of `UnaryPixelOps.PosterizePixel` were converted from `byte[]` to `ImmutableArray<byte>`

- Pinta.Core/Effects/UnaryPixelOps.cs
Most of them aren't inherited from, so I sealed them to avoid confusion.
Also, fixed one name violation I found on the way
> Sealed most classes in `UnaryPixelOps`

- Pinta.Core/Classes/DocumentSelection.cs
It already wasn't written to, except when constructing the object, so it doesn't break anything.
> Made `DocumentSelection.Clipper` a readonly property

- Pinta.Core/Classes/Palette.cs
This is in order to make `LoadDefault` clearer, and to prepare the code for more changes to come
> Default colors were moved to a generator in `Palette`

- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
The respective `Span<PointD>` is initialized completely in every iteration of the `for` loop before it's used, so it should be fine
> `Effects.CurvesDialog.DrawSpline` now uses stack allocation for line calculations

- Pinta.Core/Effects/RgbColor.cs
There is no code modifying them
After that I was able to make the `struct` itself `readonly`.
> `RgbColor` member fields were made `readonly`

- Pinta.Core/Classes/SurfaceDiff.cs
The `struct` itself remains mutable, but in a future pull request the code could be carefully changed to allow for it being immutable
> Mutation-based `DiffBounds.Merge` in `SurfaceDiff` was made into `AsMerged`, which returns new value

- Pinta.Core/Effects/ColorBgra.cs
They are redundant because they are already defined in `Utility`
> Removed clamping methods from `ColorBgra`

- Pinta.Core/Classes/DocumentSelection.cs
Originally opened in #412 , but rebase messed up the diff
> Removed dangerous cast in `DocumentSelection.ConvertToPolygons`

- Pinta.Effects/Effects/MotionBlurEffect.cs
In `MotionBlurData` we can see that the maximum value for `Distance` is 200:
```csharp
[Caption ("Distance"), MinimumValue (1), MaximumValue (200)]
public int Distance = 10;
```
So in the worst-case scenario, the number of items will be 301, because it's calculated as `(1 + Data.Distance) * 3 / 2`. If a `PointD` has a size of 16-bytes, the total number of bytes allocated on the stack is 4816, which is not too bad.
> Array used in calculation inside `MotionBlurEffect.Render` is now being allocated on the stack

- Pinta.Effects/Adjustments/HueSaturationEffect.cs
The reason for this is that, if the data changes, the chosen `UnaryPixelOp` will be invalid every subsequent time. I think this is a potential source of bugs.
This pull request is intended to bring to attention the fact that there is something similar happening in many other effects, and ask if it's intended or not. My guess is that it's not intended that way. I see that when effects are used, care is taken to alter the initial `EffectData` _before_ calling the `Render()` method.
The answer to this question will inform my future changes.
> (Pilot improvement) `HueSaturationEffect.op` is now being calculated every time

- Pinta.Effects/Effects/RedEyeRemoveEffect.cs
Also, there was an event handler attached to "PropertyChanged" of the effect data, but the data is just public fields, so nobody is getting notified of the property change. This solves the issue, as the fields will be read anyway. The end goal is getting rid of the `PropertyChanged` event.
> `UnaryPixelOp` used in `Render()` method of `RedEyeRemoveEffect` is now created every time the method is called

- Pinta.Core/Effects/Histogram.cs
- Pinta.Core/Effects/HistogramRGB.cs
This gets rid of a null-forgiving operator
> `visualColors` array in `Histogram` is now required in `Histogram`'s constructor

- Pinta.Core/Classes/Rectangle.cs
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Core/Extensions/GdkExtensions.cs
- Pinta.Gui.Widgets/Widgets/AnglePickerGraphic.cs
- Pinta.Tools/Brushes/PlainBrush.cs
- Pinta.Tools/Handles/MoveHandle.cs
- Pinta.Tools/Tools/GradientTool.cs
- Pinta.Tools/Tools/SelectTool.cs
- Pinta.Tools/Tools/TextTool.cs
Those places where these methods are called are now using variable reassignment, and calling `RectangleD.Inflated()` and `RectangleI.Inflate()` instead
> Removed mutation-based `RectangleD.Inflate` and `RectangleI.Inflate` methods

- Pinta.Core/Classes/Rectangle.cs
So now `RectangleD` is effectively immutable.
The same remains to be done for `RectangleI`
> Ascertained that `RectangleD` and its fields are `readonly`

- Pinta.Gui.Widgets/Widgets/HScaleSpinButtonWidget.cs
As a result, the controls inside this class can be made `readonly` too
> `Build()` method in `HScaleSpinButtonWidget`, which is only called inside constructor, was removed, and its body was moved to the constructor itself.

- Pinta.Gui.Widgets/Widgets/PointPickerWidget.cs
As a result, the controls inside this class could be made `readonly`
> `Build()` method in `PointPickerWidget`, which is only called inside constructor, was removed, and its body was moved to the constructor itself.

- Pinta.Gui.Widgets/Widgets/ColorGradientWidget.cs
- Fixed naming violations (`xpad` and `ypad`)
- Made it so that triangle points are allocated on the stack instead of the heap (`DrawTriangles()` method)
- Made it so that event handler doesn't need to be null-checked (see very bottom of code diff). I'd like to know what you think of this approach
> Assorted improvements and optimizations in `ColorGradientWidget`

- Pinta.Core/Managers/LayerManager.cs
This pull request is intended to bring the approach to attention. Should it be used in other places, too?
> In `LayerManager`, initialized event handlers so that they don't have to be null-checked

- Pinta.Gui.Addins/AddinListViewItem.cs
This is one of those situations where a field is created that should really be a local variable
> Removed unused field in `AddinListViewItemWidget`

- Pinta.Core/Classes/SurfaceDiff.cs
- Pinta.Gui.Widgets/Widgets/StatusBarColorPaletteWidget.cs
- Pinta/MacInterop/Carbon.cs
Refactoring has made apparent that certain fields are only modified from the constructor, in a way that code analyzers can detect.
> Made a few more fields `readonly`

- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
Also, the declaration of some variables was moved closer to where they are first used
> Removed unnecessary variable reassignments in `Effects.Levels.Dialog.cs`

- Pinta.Effects/Effects/RadialBlurEffect.cs
They were being initialized to `0` and then the values added, instead of initializing them to the values directly.
> Compacted code of `Render` in `RadialBlurEffect` by a few lines

- Pinta/Actions/File/NewDocumentAction.cs
You'll see that these variables are assigned a value no matter what, so there's no need to initialize them to dummy values
> Removed unnecessary variable assignments

- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
- Pinta.Gui.Widgets/Widgets/ComboBoxWidget.cs
**In `ComboBoxWidget`**
- Made constructor receive an `IEnumerable<string>` instead of a `string[]`
**In `SimpleEffectDialog`**
- Removed nullability in certain value types
- Modernized event handler delegate syntax
- Calls to `ComboBoxWidget` constructor don't have to materialize the items to an array
> Assorted improvements in `SimpleEffectDialog` and `ComboBoxWidget`

- Pinta.Tools/Brushes/SquaresBrush.cs
Theta is a constant, so its sine and cosine are constants too.
I don't know if this effect will be tweaked in the future (and possibly other values of theta would be needed), but for now it should be fine because I left comments that explain what the reasoning behind the constants is.
> Algebraic simplification in `SquaresBrush`

- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
The project is being compiled with `<Nullable>`, so some checks are not necessary
> Removed unnecessary `null` check in `Effects.LevelsDialog.cs`

- Pinta.Tools/Handles/MoveHandle.cs
They are never read from the outside.
Also, got rid of variable reassignment in `ContainsPoint`, and split the body of `UnionInvalidateRects` into several lines, for readability
> Fields that define default colors in `MoveHandle` were made `private`

- Pinta.Core/Managers/SettingsManager.cs
I think it can be moved down even further, but it has to be done carefully.
Also, moved `LoadSettings` to constructor
> In SettingsManager, moved exception handling one level down the call stack (from `SaveSettings()` to `DoSaveSettingsBeforeQuit()`)

- Pinta.Tools/Brushes/PlainBrush.cs
On the way, I also got rid of a variable reassignment (see `inflated`)
> Extracted code from `PlainBrush.OnMouseMove` into several, shorter methods

- Pinta.Core/Effects/UnaryPixelOps.cs
- Pinta.Effects/Adjustments/AutoLevelEffect.cs
Also, one of the public fields of its nested classes was turned into a property with the appropriate accessor visibility
> `UnaryPixelOps` was made `static`

- Pinta.Core/Classes/Layer.cs
- Pinta.Core/Classes/UserLayer.cs
- Pinta.Core/HistoryItems/TextHistoryItem.cs
- Pinta.Tools/Tools/TextTool.cs
And now the accessibility is clearly specified. All of them have `get`ters, but not all of them have `set`ters, or at least their scope is restricted to where they are actually used.
This doesn't mean that it should stay this way, but it will help us track where the values are actually used.
> Public fields of `UserLayer` were turned into properties

- Pinta/MacInterop/ApplicationEvents.cs
On the way, I changed the `Documents` property of `ApplicationDocumentEventArgs` to a read-only structure
> Fixed naming violations in `ApplicationEvents`

- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
Also, I haven't done it so far, but I've seen places in the code that would benefit from the occasional, carefully-placed `goto` inside small methods. I would like to know what you think about it... It feels weird to even ask 😅 but I don't say it lightly.
Understandably, you might want an example, so consider what happens it we turned...
```csharp
private void HandleRight (ToolKeyEventArgs e)
{
if (SelectedPointIndex < 0)
return;
if (e.IsControlPressed) {
//Change the selected control point to be the following one.
ShapeEngine? activeEngine = ActiveShapeEngine;
if (activeEngine != null) {
++SelectedPointIndex;
if (SelectedPointIndex > activeEngine.ControlPoints.Count - 1) {
SelectedPointIndex = 0;
}
}
} else {
//Move the selected control point.
var originalPosition = …
```
> Extracted code from `BaseEditEngine.HandleKeyDown()` into several smaller methods, and reduced nesting levels in a lambda

- Pinta.Core/Classes/Point.cs
The point to the right side of the operator is treated as a vector of sorts.
One idea I have is passing `PointI` to the various `OnMouseMove` methods, although I wonder if it's a good idea, given that classes like `BasePaintBrush` are marked with the attribute `Mono.Addins.TypeExtensionPoint`. I know that there's a project (Pinta-Community-Addins) that encourages Pinta add-in to register their add-ins there, but would that breaking change be worth it?
If the above is not a viable option, feel free to just close this pull request.
> Added `-` and `+` operators to `PointI` and `PointD`

- Pinta.Effects/Effects/WarpEffect.cs
I don't like that fields are assigned inside the call to `Render`, and I would like to fix that in the future. In any case, the smaller methods make this easier to see.
> Split `WarpEffect.Render` into several, smaller methods

- Pinta.Core/Classes/Angle.cs
- tests/Pinta.Core.Tests/AngleTest.cs
An idea I've got is to have this data type (especially, but not exclusively) in the effect data objects, instead of a `double`, in order to represent angles.
A potential issue is that the rounding errors that we get when converting from one unit to another could give us false negatives if we want to compare angles of different units for equality. One possibility could be making it a `class` instead of a `struct`, and use inheritance to make them unit-safe at the type level, although comparisons would require a prior conversion.
Also, if we make it into a `class` it would require heap allocations, but this might be fine still.
> Creating `Angle` structure

- Pinta.Core/Effects/BitMask.cs
- tests/Pinta.Core.Tests/BitMaskTest.cs
I'm doing this because these operations will be useful for a brush I want to make, but they could be useful on their own regardless. They include:
- Flip vertically
- Flip horizontally
- AND
- OR
- XOR
- NOT
- Clone
- Creation of submask (cloning an area)
Next, I plan to create bitmask views, but that's for another pull request
> Additional operations for `BitMask`

- Directory.Packages.props
- Pinta.Core/Actions/LayerActions.cs
- Pinta.Core/Classes/Re-editable/Text/TextEngine.cs
- Pinta.Core/Extensions/GdkExtensions.cs
- Pinta.Core/Extensions/GdkPixbufExtensions.cs
- Pinta.Core/Extensions/GtkExtensions.cs
- Pinta.Core/ImageFormats/GdkPixbufFormat.cs
- Pinta.Core/ImageFormats/OraFormat.cs
- Pinta.Gui.Widgets/Widgets/Ruler.cs
- Pinta.Resources/ResourceManager.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Tools/TextTool.cs
- Pinta.Tools/Tools/ZoomTool.cs
- Pinta/Main.cs
- Pinta/MainWindow.cs
- tests/Pinta.Effects.Tests/Utilities.cs
- tests/PintaBenchmarks/Utilities/TestData.cs
- Update for API changes to GError exception handling
- Constructors such as GLib.Bytes.New() are now generated, replacing old manual bindings
- Opaque records such as Gdk.FileList are better supported.
This is blocked on:
- https://github.com/gircore/gir.core/issues/957
> Update to the latest version of gir.core

- Pinta.Effects/Effects/CloudsEffect.cs
- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
It appears that only `CloudsEffect` is using this.
Notice, however, that the attributes `MinimumValue` and `MaximumValue` were being ignored inside the `CreateSeed` method, so I added code to handle them, but also removed these attributes from `CloudsData` itself, as the effect seems to be working fine as is.
I updated the relevant documentation:
https://github.com/PintaProject/Pinta/wiki/SimpleEffectDialog-Reference/#random-seed
> Modified `SimpleEffectDialog` to use `RandomSeed`, and changed effects that were using that mechanism

- Pinta.Core/FriendAssemblies.cs
I think that certain things in the codebase that should really be `internal` are `public` not because it makes sense to make them part of the public API, but because they need to be visible from other Pinta projects (for example when testing them). Adding this file would make it possible to make more things `internal`
> `Pinta.Core` internals visible to other assemblies

- Pinta.Core/Classes/Re-editable/Text/TextEngine.cs
- Pinta.Core/Effects/Histogram.cs
- Pinta.Core/Effects/HistogramRGB.cs
- Pinta.Core/PaletteFormats/GimpPalette.cs
- Pinta.Core/PaletteFormats/PaintShopProPalette.cs
- Pinta.Gui.Addins/AddinManagerDialog.cs
- Pinta.Gui.Addins/InstallDialog.cs
- Pinta.Tools/Editable/EditEngines/ArrowedEditEngine.cs
In general, the rule is:
- `IReadOnlyList<T>` for arrays that are being created by the method called
- `ReadOnlySpan<T>` for arrays that are merely being referenced _and_ only being read
- `Span<T>` for arrays that are merely being referenced _and_ being written
> Some variables of array types were converted to `Span<T>` , `ReadOnlySpan<T>`, or `IReadOnlyList<T>`

- .github/workflows/build.yml
- .github/workflows/dotnet7.global.json
- CHANGELOG.md
- Directory.Build.props
- configure.ac
- readme.md
Building against .NET 7 is still supported for now
> Upgrade to .NET 8

- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Core/Extensions/GdkPixbufExtensions.cs
- Pinta.Core/Extensions/GtkExtensions.cs
- Pinta.Core/Extensions/PangoExtensions.cs
- Pinta/MacInterop/AppleEvent.cs
- Pinta/MacInterop/Carbon.cs
- Pinta/MacInterop/CoreFoundation.cs
- Pinta/MacInterop/Environment.cs
This is originally from #563 , but at the time building with .NET 6.0 (which doesn't have this feature) was supported. But I see that since then .NET 8.0 became a requirement.
Not all existing `DllImport` attributes were replaced, as they could cause problems in cases like string marshalling and similar, but they should be visible in the diff, because I added access modifiers.
> Replaced `DllImportAttribute` with `LibraryImportAttribute` in order to generate P/Invoke marshalling code at compile time

- Pinta.Core/Effects/ColorDifferenceEffect.cs
- Pinta.Core/Effects/HistogramRGB.cs
- Pinta.Core/Effects/UnaryPixelOps.cs
- Pinta.Effects/Adjustments/BrightnessContrastEffect.cs
- Pinta.Effects/Effects/AddNoiseEffect.cs
- Pinta.Effects/Effects/InkSketchEffect.cs
- Pinta.Effects/Effects/LocalHistogramEffect.cs
- Pinta.Effects/Effects/OilPaintingEffect.cs
- Pinta.Effects/Effects/RadialBlurEffect.cs
- Pinta.Effects/Effects/ZoomBlurEffect.cs
- Pinta.Tools/Tools/RecolorTool.cs
It could get confusing in situations where we just need to read a value (so a copy of the value on the stack is ok).
When the `ref readonly`s were returned by a method as such (specifically `CairoExtensions.GetColorBgra`) they were not removed.
I presume that the original intention of the code was to have an actual reference to the current color of the pixel in question, as opposed to a snapshot of it, such that the code always reads the updated pixel. In practice, though, the code seems to be single-threaded at that level, but even if it weren't, the pixel isn't terribly likely to change while its individual components are being read (the length of the time where this happens is just very short).
A possible use case for `readonly ref` is using the data of the pixel to update that same …
> Removed `ref readonly` for array accesses

- Pinta.Effects/Effects/GlowEffect.cs
Otherwise the call to `Render()` modifies the internal state of `GlowEffect`, which is very questionable
> In `GlowEffect`, turned auxiliary sub-effects from fields to local variables

- CHANGELOG.md
- Pinta.Core/Actions/ViewActions.cs
- Pinta/Actions/View/ColorSchemeChangedAction.cs
- Pinta/DialogHandlers.cs
- Pinta/Main.cs
- Pinta/MainWindow.cs
This uses AdwStyleManager's facilities for specifying whether the light or dark variant of the system theme should be used. If the system doesn't indicate a preference, the default is to use dark.
> Support switching between light and dark themes

- Pinta.Core/Effects/ColorBgra.cs
- Pinta.Core/Effects/GradientRenderer.cs
- Pinta.Core/Effects/UnaryPixelOps.cs
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Effects/Effects/AddNoiseEffect.cs
- Pinta.Effects/Effects/InkSketchEffect.cs
- Pinta.Effects/Effects/RadialBlurEffect.cs
- Pinta.Effects/Effects/ZoomBlurEffect.cs
- Pinta.Tools/Tools/EraserTool.cs
- Pinta.Tools/Tools/RecolorTool.cs
Also, some occurrences where its members are mutated were replaced by `ColorBgra.FromBgra()`. I don't know how feasible it is to make `ColorBgra` a `readonly` `struct`, but this may be a step in the right direction
> Removed a few `ref`s to `ColorBgra` used to modify pixel colors

- Pinta.Effects/Effects/AddNoiseEffect.cs
- Created `AddNoiseSettings`, for consistency with other effects, but also to get the reference to `Data.Seed` out of the `foreach` loop. From previous (subjective) experience, casting the `EffectData` object every time slows down the rendering noticeably.
- Removed a nesting level by getting rid of an `else` block. I think it's still clear enough
- Reduced variable reassignment inside `for` loop
> Local refactorings in `AddNoiseEffect`

- Pinta.Core/Managers/LivePreviewManager.cs
This is a fairly unintrusive change to support non-tileable effects. If the effect isn't tileable, we just create a single tile for the whole render bounds.
Related to PR #457
> Support rendering non-tileable effects

- Pinta.Core/Effects/ColorBgra.cs
In the second commit I also shortened `UInt32` to `uint`, if this is not desired, the commit could be discarded
> Simplified/modernized/shortened code in `ColorBgra`

- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
Also, separated the extraction of configuration and the creation of widgets into separate methods, and did some more refactorings aimed at reducing redundancy and increasing type safety.
The end goal is that, after enough refactoring, everything (or most of it) is type-safe and can be done at the runtime level (through generics, for example)
> `SimpleEffectDialog` now receives strongly-typed `EffectData`

- Pinta.Core/Classes/Point.cs
- Pinta.Core/Effects/Utility.cs
- Pinta.Effects/Effects/JuliaFractalEffect.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
- Pinta.Effects/Effects/PolarInversionEffect.cs
In first commit:
- Methods in `PointI` and `PointD` that calculate magnitude and distance were moved to `Utility` as extension methods
- Created `Utility.MagnitudeSquared` and got some effects to use it
In second commit:
- Made `Utility.Lerp` generic, made possible thanks to `INumber<TSelf>` and [static virtual members](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/static-virtual-interface-members)
In third commit:
- Made `InvLerp` generic, similar to how it was done for `Lerp`
In fourth commit:
- Made `GetRegionBounds` more concise
> Extracted some mathematical functions into `Utility`

- Pinta.Core/Effects/HsvColor.cs
- Pinta.Effects/Effects/ColorGradient.cs
- Pinta.Effects/Effects/JuliaFractalEffect.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
I think the current selection of gradients for the fractals could be a bit dull, so what if we make it wider by adding customization options?
In the first commit, I added the option of reversing the gradient (turning the gradient upside down):
At some point I added the option of rotating the hue of the colors in the gradient. However, in the last commit I removed the `HueRotation` property in the `EffectData`. because the user can just use **Adjustments > Hue / Saturation**; but if you think that keeping that property is a good idea, you could drop the last commit.
> Added new methods to gradients, and customization options to fractals that use them

- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
Originally just wanted to fix a naming violation, but I could do this on the way so that the changes are worth it
> Reformatting in `Effects.LevelsDialog.cs`

- Pinta.Core/Effects/Utility.cs
- Pinta.Gui.Widgets/Widgets/HistogramWidget.cs
One unintended consequence of making these methods generic on `INumber` is that when the type inference determines that the type is an integer, the result will be truncated, and when that results in an inaccurate calculation it could be hard to determine where the error is, so now it's only values of type `IFloatingPoint<TSelf>`
> Made generic constraints in `Utility.Lerp` and `Utility.InvLerp` more specific

- Directory.Packages.props
- Pinta.Core/Classes/Re-editable/Text/TextEngine.cs
- Pinta.Core/Extensions/GdkExtensions.cs
- Pinta.Core/Extensions/GdkPixbufExtensions.cs
- Pinta.Core/Extensions/GtkExtensions.cs
- Pinta.Core/Extensions/PangoExtensions.cs
- Remove manual bindings that are now generated correctly upstream
- The PixbufFormat constructor now requires an owned handle
> Upgrade to the latest gir.core release

- Pinta.Core/Effects/Utility.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
Specifically, some values used for calculation look as if they were customizable when they aren't so they were made constant. I figured that if we are going to customize them at some point, we can always make them non-constants.
Also tried to make the code more semantic here and there in a few ways. For example, the `angleTheta` setting is now of type `RadiansAngle`.
> Simplified Mandelbrot code

- Pinta.Effects/Effects/ColorGradient.cs
Originally I wrote a method, `BinarySearchHigherOrEqual`, in order to convert `BinarySearch`'s return value into what I wanted to use, but shortly after it dawned on me that it's probably better to use `BinarySearch`'s return value directly
> Shortened gradient stops search code

- Pinta.Core/Classes/PixelOffset.cs
- Pinta.Core/Effects/ColorDifferenceEffect.cs
- Pinta.Core/Effects/Utility.cs
- Pinta.Effects/Effects/AddNoiseEffect.cs
- Pinta.Effects/Effects/BulgeEffect.cs
- Pinta.Effects/Effects/DitheringEffect.cs
- Pinta.Effects/Effects/JuliaFractalEffect.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
- Pinta.Effects/Effects/MotionBlurEffect.cs
- Pinta.Effects/Effects/OilPaintingEffect.cs
- Pinta.Effects/Effects/PencilSketchEffect.cs
- Pinta.Effects/Effects/SoftenPortraitEffect.cs
- Pinta.Effects/Effects/TileEffect.cs
- Pinta.Effects/Effects/TwistEffect.cs
- Pinta.Effects/Effects/VoronoiDiagramEffect.cs
- Pinta.Effects/Effects/WarpEffect.cs
Some simple values are re-calculated with each pixel, but I plan to solve it with another structure that stores values for each row or column. The code of some effects is not that easy to refactor in this way yet, though.
Also, I'm noticing that `SoftenPortraitData.Softness` and `SoftenPortraitData.Lighting` aren't being used anywhere?
> Several effects refactored to use `Utility.GeneratePixelOffsets`

- Pinta.Core/Classes/DocumentSelection.cs
This PR aims to close my issue (#661).
It doesn't implement any GUI options, but hopefully it makes the job much easier for people that know how to add the buttons.
I have tried my best to respect the project coding practices but i am kinda new to doing pull requests, so i would really like if this was tested first.
To get into technical details, i have chosen the "jtMiter" JoinType as i think it's the most fitting between [these options](https://angusj.com/clipper2/Docs/Units/Clipper/Types/JoinType.htm).
> added Offset method to selection class

- Pinta.Gui.Widgets/DialogAttributes.cs
These are part of the public API. It doesn't make sense that we are letting them open for inheritance if we are just going to use the parent class.
> Sealed classes in `DialogAttributes`

- CHANGELOG.md
I noticed they aren't mentioned
> Mentioned Voronoi diagrams in changelog

- Pinta.Core/Classes/BasePaintBrush.cs
- Pinta.Core/Classes/BaseTool.cs
- Pinta.Tools/Brushes/CircleBrush.cs
- Pinta.Tools/Brushes/GridBrush.cs
- Pinta.Tools/Brushes/SplatterBrush.cs
Perhaps I'm missing something, but is there a reason why all brushes share the same instance of `Random`?
If we make `Random` instance-specific, it would even be possible to test these tools with a specific seed
> Removing `Random` from `BasePaintBrush`

- Pinta.Core/Classes/BaseTool.cs
- Pinta.Tools/Tools/EraserTool.cs
- Pinta.Tools/Tools/FreeformShapeTool.cs
- Pinta.Tools/Tools/PaintBrushTool.cs
- Pinta.Tools/Tools/PencilTool.cs
- Pinta.Tools/Tools/RecolorTool.cs
The child tools that used this value were made to have a nullable `PointI` instead
> Removed `BaseTool.point_empty`

- installer/linux/install.proj
As described in documentation %(Extension) already contains a dot.
https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-well-known-item-metadata
> Fix 'uninstall' target not removing icons on linux

- Pinta.Effects/Effects/JuliaFractalEffect.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
We can see that there was a  very old (dating back to 2010) comment that read `//TODO: double` in the Mandelbrot's `EffectData`.
Also, there was a time when `SimpleEffectDialog` had no support for `double`.
Presumably, the comment (and the `int`-typed zoom) comes from that time?
> Changed data type of zoom for Mandelbrot and Julia fractals, from `int` to `double`

- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
`MemberSettings` used to have an `isComboBox` property, but it doesn't apply to every type of property, only to `string`-typed properties (for which. there is no suitable control if `StaticListAttribute` is not present, by the way`).
It could be hard to get the structure right, but hopefully these refactorings are helping.
> `StaticListAttribute` is being read closer to where it's needed in `SimpleEffectDialog`

- Directory.Packages.props
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Core/Extensions/GdkExtensions.cs
- Pinta.Core/Extensions/GdkPixbufExtensions.cs
- This contains a fix for the random crashes encountered on Windows
- The Cairo.Matrix class now has a more convenient constructor
- Gdk.FileList.GetFiles() is not being generated and requires a manual binding for now, but GLib.SList methods are now generated
Fixes: #674
> Update to gir.core 0.5.0

- Pinta.Gui.Widgets/Widgets/AnglePickerWidget.cs
It seems that under the hood, everything is using `double` to represent angles, so the limitation of rotation to integers is entirely a UI issue. This PR updates the UI to use a standard Gtk SpinButton feature to permit two decimal places in the angle input when rotating a layer. This doesn't affect the step size for the + / - buttons. Tested, seems to be working. :-)
> Add support for rotation by fractional degrees

- Pinta.Tools/Editable/Shapes/Arrow.cs
The main things that were done were:
- Limiting the visibility of property setters
- The return value of `Draw` was ascertained to be non-nullable
> Small refactorings in `Arrow`

- Pinta.Core/Classes/Rectangle.cs
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Gui.Widgets/Widgets/ColorGradientWidget.cs
- Pinta.Gui.Widgets/Widgets/Ruler.cs
- Pinta.Tools/Brushes/SplatterBrush.cs
Also, `RectangleD` was turned into a proper positional record, so that it's easier to create implementations of new methods like `Union` (because such implementations can be based on `RectangleI`'s) and use them when appropriate (for example, `CairoExtensions` contains the `UnionRectangles` method, which could presumably be easily removed if `RectangleD` had a `Union` method).
For the compilation to work, I had to modify several call sites, and several small improvements were made in the files touched by that change.
> Small refactorings and syntax modernization for `CairoExtensions`

- Pinta/Actions/Addins/AddinManagerAction.cs
- Pinta/Actions/Edit/OffsetSelectionAction.cs
- Pinta/Actions/Edit/PasteAction.cs
- Pinta/Actions/Edit/PasteIntoNewImageAction.cs
- Pinta/Actions/Edit/PasteIntoNewLayerAction.cs
- Pinta/Actions/Edit/ResizePaletteAction.cs
- Pinta/Actions/File/CloseDocumentAction.cs
- Pinta/Actions/File/ExitAction.cs
- Pinta/Actions/File/ModifyCompressionAction.cs
- Pinta/Actions/File/NewDocumentAction.cs
- Pinta/Actions/File/NewScreenshotAction.cs
- Pinta/Actions/File/OpenDocumentAction.cs
- Pinta/Actions/File/SaveDocumentAction.cs
- Pinta/Actions/File/SaveDocumentAsAction.cs
- Pinta/Actions/File/SaveDocumentImplementationAction.cs
- Pinta/Actions/Help/AboutDialogAction.cs
- Pinta/Actions/Image/ResizeCanvasAction.cs
- Pinta/Actions/Image/ResizeImageAction.cs
- Pinta/Actions/Layers/LayerPropertiesAction.cs
- Pinta/Actions/Layers/RotateZoomLayerAction.cs
- Pinta/Actions/View/ColorSchemeChangedAction.cs
- Pinta/Actions/View/ImageTabsToggledAction.cs
- Pinta/Actions/View/StatusBarToggledAction.cs
- Pinta/Actions/View/ToolBarToggledAction.cs
- Pinta/Actions/View/ToolBoxToggledAction.cs
- Pinta/Actions/Window/CloseAllDocumentsAction.cs
- Pinta/Actions/Window/SaveAllDocumentsAction.cs
- Pinta/Dialogs/JpegCompressionDialog.cs
Originally, the idea was to change (or even get rid of) `IActionHandler` and the constructors of the actions, so that they don't depend on global context like `PintaCore`, but I think it would require some thought.
The refactoring is mostly done in bulk in order to get rid of ugly patterns like `#region IActionHandler Members`, but there are some where special care was taken, like `OpenDocumentAction`.
On the way, `JpegCompressionDialog` was also modified
> Refactoring of all action handlers

- Pinta.Gui.Widgets/Widgets/Canvas/CanvasRenderer.cs
- Pinta.Gui.Widgets/Widgets/Layers/LayersListViewItemWidget.cs
In `LayersListViewItemWidget`, control creation was moved to its own methods.
In `CanvasRenderer`, certain syntax was modernized, a method signature (`Render()`) was modified, and variable declaration was done with specific types whenever it resulted in clearer code.
> Miscellaneous refactorings in `LayersListViewItemWidget.cs` and `CanvasRenderer`

- Pinta.Tools/Tools/EraserTool.cs
There is a combobox which _does_ initialize to the last-used mode, but the value doesn't actually get stashed into the tool's state, so until you interact with it, it's still in the default state. In practice, this means that if you use the eraser tool and set it to `Smooth` mode, then you restart Pinta, the combo box remembers that it should be in `Smooth` mode, but the tool initially operates in `Normal` mode.
This PR sets the tool's state to match the value loaded into the combo box.
> Bug fix: Eraser tool does not initialize to last-used mode

- Pinta.Effects/Effects/CloudsEffect.cs
- Pinta.Gui.Widgets/Dialogs/MemberReflector.cs
- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
`CloudsData` has a static property `BlendOps`, which `SimpleEffectDialog` tried to use and caused an error to occur because it doesn't have a getter, but again, this property is static and isn't supposed to be used. I added some more checks in the filtering part in order to make sure that only instance properties are used.
Still, I don't think this property belongs in `CloudsData`, so I moved it to `CloudsEffect`. If this is not desired, the last commit could be discarded.
> Ensured that only instance properties (and no static properties) are used in `SimpleEffectDialog`

- Pinta/Actions/File/NewDocumentAction.cs
- Pinta/Dialogs/NewImageDialog.cs
I've identified some patterns used in the creation of dialogs, which I've abstracted into methods. I plan to move these methods to `GtkExtensions` (or some other class, as appropriate) in a future pull request, and then get other dialog classes to use them. The end goal would be having a convenient way to lay items out and effortlessly have a consistent visual style throughout the application.
> Refactored control creation in constructor of `NewImageDialog`

- Pinta.Gui.Widgets/Dialogs/ReflectionHelper.cs
- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
Otherwise the lookup in `BlendOps` from `CloudsEffect` might just fail anyway because it is a `ReadOnlyDictionary`, but with this change it should work with any dictionary structure.
Also, made messages in exceptions more informative.
> Combobox creation in `SimpleEffectDialog.CreateComboBox()` now looks for an `IDictionary<T>`, and not a `Dictionary<T>`

- Pinta.Core/Classes/Document.cs
- Pinta.Core/Classes/Layer.cs
When you finish a selection with pixels that aren't fully-opaque (whether due to layer opacity or the pixels' alpha channel), those pixels are blended with the target layer according to the opacity, but this is not the proper semantic for a selection. If you create a selection and then use Move Selection tool to relocate it, within that layer, the pixels' opacity should simply be translated along with the colour. This PR fixes selection moves so that when the selection is "dropped" onto the underlying layer, it simply replaces all of the pixels involved. It implements this by still blending the pixels the way it did before, but by clearing the underlying pixels so that there's nothing there for them to blend with. The new blend method ignores the layer opacity as well.
There is a separate …
> Bug fix: Handling of alpha pixels when committing selection

- Pinta.Core/Managers/WorkspaceManager.cs
- tests/Pinta.Effects.Tests/Mocks/MockWorkspaceService.cs
- tests/PintaBenchmarks/Mocks/MockWorkspaceService.cs
This helps identify what part of the public interface is actually needed, and which part is just a convenience.
I managed to remove one method from the `IWorkspaceService` interface itself.
The code that uses the service should be able to work without changes.
> Moved some `WorkspaceManager` code to extension methods

- Pinta.Effects/Effects/DentsEffect.cs
Similar to what happened in `VignetteEffect`, I don't see the comment for translators being picked up in this case
> Fix formatting so translator comments are picked up in `DentsEffect`

- Pinta.Core/Classes/AsyncEffectRenderer.cs
- Pinta.Core/Managers/LivePreviewManager.cs
This is a first step towards handling parallelism inside the effect itself instead of doing it in the LivePreviewManager, as discussed in #808, as identifying the moving parts could be useful in abstracting them away and ultimately achieving our goal (not re-calculating all of the settings for every tile).
> Settings for `AsyncEffectRenderer` were made immutable

- CHANGELOG.md
- Pinta/Actions/File/SaveDocumentImplementationAction.cs
This fixes #914
It's a pretty simple fix, simply manually setting the directory and name back to the value the user picked before re-opening the dialogue.  
This fixes the issue on Linux, but testing on Mac and Windows would be nice to ensure there isn't any regression.
> Re-set name and directory in the file picker dialogue when a save fails

- Pinta.Core/Classes/Document.cs
- Pinta.Tools/Brushes/PlainBrush.cs
- Pinta.Tools/Tools/PaintBrushTool.cs
Each line segment of the stroke in the PlainBrush is drawn independently, one after another. With semitransparent colors, the line segments overlap each other on their ends, causing the dark dots in the stroke.
Upon `OnMouseDown()`, we create a Cairo Path variable called `path`  as a class member, set it to null, and show the ToolLayer.
During `OnMouseMove()` events, we operate on the ToolLayer surface and clear it before drawing (we only clear for the PlainBrush), append `path` to the cairo context and after stroking, copy the new path back to the class member. Cairo will draw the entire path in one go, which gets rid of the dark dots. Performance hit is negligible.
In `OnMouseUp()` we draw the contents of the ToolLayer onto the destination Layer, clear and hide it.
The Pencil Tool isn't …
> Fix dotted brushstrokes when drawing with semitransparent colors

- Pinta.Core/Classes/BaseTool.cs
- Pinta.Tools/Tools/TextTool.cs
I was frustrated with the lack of ability to disable antialiasing on Pinta, so I decided to just go and add it.
Please note this was cobbled together. I have zero experience with Cairo/Pango/PangoCairo but in my brief testing there didn't seem to be any obvious problems.
Thank you in advance.
> Add antialiasing toggle to text tool

- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Gui.Widgets/Widgets/HistogramWidget.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Editable/EditEngines/EllipseEditEngine.cs
- Pinta.Tools/Editable/EditEngines/LineCurveEditEngine.cs
- Pinta.Tools/Editable/EditEngines/RectangleEditEngine.cs
- Pinta.Tools/Editable/EditEngines/RoundedLineEditEngine.cs
- Pinta.Tools/Editable/Shapes/EllipseEngine.cs
- Pinta.Tools/Editable/Shapes/LineCurveSeriesEngine.cs
- Pinta.Tools/Editable/Shapes/RoundedLineEngine.cs
- Pinta.Tools/Editable/Shapes/ShapeEngineCollection.cs
- tests/Pinta.Core.Tests/DashPatternTest.cs
Fixes #733
I had discovered what caused bug #733 was that "-" and "" are treated differently by the dash engine. So it wasn't noticeable at lower widths, but at larger widths it would cause those artifacts. This fix defaults the "-" dash pattern to "" internally, preventing this issue and drawing it as the user expects.
This approach may be considered a little too hacky? An alternative would be to make the default dashpattern "".
However, this led to a second issue, was that the polygon engine auto-defaults to use `LineCap.Square`. This would produce another artifact in drawing the circle. Defaulting to LineCap.Butt would fix this issue, but it would break rectangle drawing, and hard-coding in to make an exception for ellipse drawing would suck.
So i modified the polygon engine to support …
> Fixes to shape drawing

- Pinta.Tools/Tools/TextTool.cs
Fixes #952 
Redraws of text tool from font updates and color palette changes are not completely blocked by the variable is_editing anymore, it no longer blocks when CurrentTextEngine's state is NotFinalized . Fix works on Windows for me, but have not checked Linux or Mac.
> Allow text tool changes to redraw text when state is NotFinalized #952

- Pinta.Core/Classes/DocumentLayers.cs
Fixes the bug described in #951 about incorrect cutting/pasting behavior.
Previously, the clipping operation would incorrectly include everything within the outer bounds of the selection, even when the selected area contained unselected regions.
This fix makes sure that inner regions are correctly handled as shown in the video.
https://github.com/user-attachments/assets/e454c41a-d632-449c-a0a0-4b8406c667a7
> Fix incorrect cutting/pasting behavior #951 

- Pinta.Core/Classes/DocumentLayers.cs
Fixes issue: #979
Added a call to `Workspace.Invalidate()` in `DocumentLayers.DeleteLayer()` and `DocumentLayers.Insert()` to always update the canvas when a layer is deleted or inserted.
Another alternative would be to invalidate the workspace from the LayerAction that deletes the layer, and from `Undo()`/`Redo()` in `DeleteLayerHistoryItem` if that is preferred?
> Fix canvas not updating when deleting layers or redoing/undoing layer changes

- Pinta.Effects/Effects/OutlineObjectEffect.cs
Along with a few minor things such as using explicit variable types and removing certain intermediate variables (those which correspond to properties that we can just read from `roi`)
> Decreased nesting in `OutlineObjectEffect`

- Pinta.Core/Classes/AsyncEffectRenderer.cs
- Pinta.Core/Extensions/OtherExtensions.cs
- Pinta.Core/Managers/LivePreviewManager.cs
- tests/Pinta.Core.Tests/RectangleTests.cs
This should get us a step closer towards handling parallelism inside the effects themselves, as discussed in #808
> Created method for slicing ROI into tiles, for use inside `AsyncEffectRenderer`

- Pinta.Core/Classes/AsyncEffectRenderer.cs
- Inlined `RenderTile`
- Extracted method `StartMasterThread`. Now it's obvious what the mechanism does (one tile per thread, including the master thread, which additionally coordinates the slave joins)
- Used concurrent structure for exception list, in order to remove lock
> Further refactorings in `AsyncEffectRenderer`

- Pinta.Core/Classes/AsyncEffectRenderer.cs
The `render_id` is used for cancellation only. Instead of this, we could make it clearer.
Additionally, I made certain methods local _and_ identified a better way to abort a rendering (with `return` instead of `continue`). I tried in an Ubuntu virtual machine and it feels the delay until the start of the next rendering is shorter.
There is still some way to go. If we want to handle parallelism inside the methods, the code for creating and coordinating the tiles and threads needs to be very simple and easy to understand by anyone wanting to develop an extension.
> Refactored `AsyncEffectRenderer` to use `CancellationToken`

- Pinta/Dialogs/ErrorDialog.cs
- Pinta/MainWindow.cs
- Pinta/Pads/HistoryPad.cs
- Pinta/Pads/LayersPad.cs
This required making `ErrorDialog` non-static, because `ShowError` is required to have a specific signature (see argument of `InitializeErrorDialogHandler`)
> Removed `PintaCore` references from `ErrorDialog`, `HistoryPad`, and `LayersPad`

- Pinta.Core/Extensions/CairoExtensions.cs
None of the callers seems to use it. This was refactored away maybe a year ago. One can still use `GetReadOnlyPixelData` if necessary
> Return type of `CairoExtensions.GetColorBgra` is no longer `ref readonly`

- Pinta.Core/Actions/HelpActions.cs
- Pinta.Core/DialogResponses.cs
- Pinta.Core/Extensions/GtkExtensions.cs
- Pinta.Core/Managers/ChromeManager.cs
- Pinta.Core/Messages/ErrorDialogResponse.cs
- Pinta.Gui.Addins/AddinInfoView.cs
- Pinta.Gui.Addins/AddinListView.cs
- Pinta.Gui.Addins/AddinManagerDialog.cs
- Pinta/ActionHandlers.cs
- Pinta/Actions/Addins/AddinManagerAction.cs
- Pinta/Dialogs/ErrorDialog.cs
- Pinta/MainWindow.cs
Since the response of `ErrorDialog.ShowError` doesn't have to be handled inside its body anymore, I was able to take out the system manager field out of `ErrorDialog`, which means it can be made `static` again.
I refactored `SystemManager` out of several places, trying very hard not to re-introduce `PintaCore` references to places where it was already gone, but unfortunately I had to do it temporarily inside `ChromeManager.ShowErrorDialog`, for the following reasons:
- I could delegate further and return a `Task<string>` from `ChromeManager.ShowErrorDialog`, and the caller would be responsible for opening the bug tracker, but I think it wouldn't be appropriate
- I could fix that by fixing the interdependencies between services (namely `GtkExtensions.LaunchUri` should instead be part of a …
> `ErrorDialog.ShowError` and `ErrorDialog.ShowMessage` were made asynchronous

- readme.md
This simply adds a "Get it on flathub" badge to the README, as is commonly seen for other applications available on flathub.  
This would make it instantly clear that the software works on linux without needing to build it yourself (which is currently not the case, as shown by #982), as well as how the user can install it.
> Add a flathub badge to the README

- Pinta.Core/Managers/PaletteManager.cs
- Pinta.Gui.Widgets/Widgets/StatusBarColorPaletteWidget.cs
Mostly so that the `Count` property can be used instead of the LINQ `Count()` method
> `PaletteManager.RecentlyUsedColors` is now a `ReadOnlyCollection`

- Pinta.Core/Classes/Palette.cs
- Pinta.Core/Managers/ChromeManager.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta/Actions/Edit/PasteAction.cs
- Pinta/Actions/Edit/PasteIntoNewImageAction.cs
- Pinta/Actions/File/NewScreenshotAction.cs
- Pinta/Main.cs
- Pinta/MainWindow.cs
[As discussed before](https://github.com/PintaProject/Pinta/pull/1021#discussion_r1786995885), when a dialog is shown, the caller does not care about the specific response, but it might care to know when the dialog is closed.
> Methods `ShowMessage` and `ShowError` in `ChromeManager` made asynchronous

- Pinta.Core/Extensions/GtkExtensions.cs
- Pinta.Effects/Adjustments/CurvesEffect.cs
- Pinta.Effects/Adjustments/LevelsEffect.cs
- Pinta.Effects/Adjustments/PosterizeEffect.cs
- Pinta.Effects/Effects/AlignObjectEffect.cs
- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
In the first commits, the method is returning an `int` corresponding to the response ID.
In the last two commits, the method is returning an `Gtk.ResponseType`
> Created (and started using) `RunAsync` extension method for `Gtk.Dialog`

- Pinta.Core/Effects/GradientRenderer.cs
- Pinta.Core/Effects/GradientRenderers.cs
I have a refactoring in mind that would make all derived classes immutable and also handle all the rendering from the outside, but doing everything in a single go would make the changes hard to review.
> Removed unused method `AfterRender` from `GradientRenderer`

- Pinta.Core/Classes/Document.cs
- Pinta.Core/ImageFormats/GdkPixbufFormat.cs
- Pinta.Core/ImageFormats/IImageImporter.cs
- Pinta.Core/ImageFormats/OraFormat.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta/ActionHandlers.cs
- Pinta/MainWindow.cs
Based on what was discussed in https://github.com/PintaProject/Pinta/pull/1012#issuecomment-2384657092
I might end up closing that one and just continuing from here.
Unfortunately, this re-introduced `PintaCore` references in the `WorkspaceManager`, but I'd argue that progress is still being made.
The `IImageImporter` interface was changed
> Moving "activate document" part out of file format class

- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
A few loop invariants were extracted.
You can see that if you distribute the multiplication done when calculating `u` and `v` there is a part that is independent of `i`
> Optimization to `MandelbrotFractalEffect` calculations

- Pinta.Effects/Effects/DentsEffect.cs
- Pinta.Effects/Effects/PolarInversionEffect.cs
- Pinta.Effects/Effects/WarpEffect.cs
Now all the necessary settings are passed as an argument.
The end goal of this is eventually getting rid of `WarpEffect`, i.e. having a flat class hierarchy so that an effect can use these mechanisms without having to inherit from that specific class.
> `InverseTransform` in `PolarInversionEffect` and `DentsEffect` is now independent of `WarpEffect`'s state

- Pinta.Effects/Effects/DentsEffect.cs
- Pinta.Effects/Effects/PolarInversionEffect.cs
- Pinta.Effects/Effects/Warp.cs
I think this would make things clearer and establish how this kind of refactoring should be done — for example, if we wanted to refactor away `ColorDifferenceEffect`, we could follow a similar structure
> All types related to warping were nested inside the `Warp` class

- Pinta.Core/Managers/LivePreviewManager.cs
The only public method is `Start`
.
This will help us refactor later, and identify the fields that are used for communication between renders. The goal is getting rid of them, because one render shouldn't have to know about other renders.
> Non-public methods in `LivePreviewManager` were made local

- CHANGELOG.md
- Pinta.Effects/Effects/TwistEffect.cs
At present, when we select a region and twist it, the calculations are done based on the whole image:
With this change, the calculations will be done based on the selected region itself:
> Applying `TwistEffect` locally based on selection

- Pinta.Core/Actions/ViewActions.cs
- Pinta.Core/Managers/CanvasGridManager.cs
- Pinta.Core/PintaCore.cs
- Pinta.Gui.Widgets/Widgets/Canvas/CanvasRenderer.cs
- Pinta.Gui.Widgets/Widgets/Canvas/CanvasWindow.cs
- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
- Pinta.Gui.Widgets/Widgets/Layers/LayersListViewItemWidget.cs
- Pinta/ActionHandlers.cs
- Pinta/Actions/View/EditCanvasGridAction.cs
- Pinta/Dialogs/CanvasGridSettingsDialog.cs
- Pinta/MainWindow.cs
- tests/PintaBenchmarks/CanvasRendererBenchmarks.cs
This extends the current pixel grid to be more customizable by allowing the user to specify the grid size as described in #1028. The original functionality of the pixel grid is still available be setting the grid width and height to 1px.
https://github.com/user-attachments/assets/ccd5470e-9f90-473a-b528-ba03c5c5b4ad
> Customizable grid size

- Pinta.Effects/Effects/GradientHelper.cs
Specifically, this is the gradient that is generated when the helper method (`GradientHelper.CreateBaseGradientForEffect`) gets passed a random seed with a value of 0. Users might miss it if the implementation changes at some point.
> Added extra pre-defined gradient

- .github/workflows/build.yml
- CHANGELOG.md
> Sign the Windows installer via SignPath

- Pinta.Core/Classes/CenterOffset.cs
- Pinta.Effects/Algorithms/Warp.cs
- Pinta.Effects/Effects/DentsEffect.cs
- Pinta.Effects/Effects/PolarInversionEffect.cs
- Pinta.Effects/Effects/RadialBlurEffect.cs
- Pinta.Effects/Effects/ZoomBlurEffect.cs
- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
- Pinta.Gui.Widgets/Widgets/PointPickerWidget.cs
- tests/Pinta.Effects.Tests/EffectsTest.cs
This should prevent the kind of confusion that led to #1125
I made the type generic in order to future-proof it a little, but if this is not desired, the last commit can be discarded.
> Created specialized offset type

- Pinta.Effects/Effects/TileEffect.cs
- Pinta.Effects/Effects/TwistEffect.cs
I had refactored `TwistEffect` in a similar way, too, but I reverted it. For some unidentified reason, the output was similar but not the same.
> Simplifying `TileEffect` to use `ColorBgra.Blend`

- Pinta.Core/Actions/EditActions.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.Dialog.cs
It is relatively straightforward.
On the other hand, migrating the part where the user saves the palette (and, more specifically, the renaming part) is a bit trickier. As far as I know, there is currently no way to know which filter the user chose. Maybe we could skip the renaming part?
> Modernized dialog for opening palette in `EditActions`

- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Tools/BaseBrushTool.cs
Implements issue #796. The square brackets ] and [ increase and decrease the brush size respectively. Applies to all tools that implement BaseBrushTool and ShapeTool.
I'm wondering if it's possible to add a tooltip to the + and - buttons on the brush size widget? As of right now there's no indication that the shortcuts exist.
> Add keyboard shortcut for changing the brush size or line width

- Pinta.Effects/Algorithms/PerlinNoise.cs
- Pinta.Effects/Effects/CloudsEffect.cs
- Pinta.Effects/Effects/DentsEffect.cs
The failure of the Mac x64 build seems unrelated
> Bundled data values and reduced variable re-assignment in `PerlinNoise` and effects that use it

- Pinta.Core/Classes/Rectangle.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
Some arguments are now received by read-only reference `in`. Also, reduced variable re-assignment in `Clamp` method, and changed its name to `Clamped`
> Small optimizations to `RectangleI` and `RectangleD`

- Pinta.Effects/Adjustments/CurvesEffect.cs
- Pinta.Effects/Adjustments/SepiaEffect.cs
- Pinta.Effects/Algorithms/PerlinNoise.cs
- Pinta.Effects/Classes/ColorGradient.cs
- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
- Pinta.Effects/Effects/FeatherEffect.cs
- Pinta.Effects/Effects/InkSketchEffect.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
- Pinta.Effects/Effects/OutlineObjectEffect.cs
- Pinta.Effects/Effects/VoronoiDiagramEffect.cs
- Pinta.Effects/Utilities/PaletteHelper.cs
I think this was removed because .NET 7 didn't support it, but now the official builds don't include .NET 7
> Terse collection initialization syntax in `Pinta.Effects`

- Pinta/Actions/Edit/OffsetSelectionAction.cs
- Pinta/Actions/Edit/ResizePaletteAction.cs
- Pinta/Actions/Image/ResizeCanvasAction.cs
- Pinta/Actions/Image/ResizeImageAction.cs
- Pinta/Actions/Layers/LayerPropertiesAction.cs
- Pinta/Actions/View/EditCanvasGridAction.cs
Not all of them. Only those for which fitting extension methods exist. The other ones require adding further extension methods to `GtkExtensions.Dialog.cs`, but that's for a future pull request
> Several action handlers that use dialogs were made `async`

- Pinta.Core/Extensions/Gtk/GtkExtensions.Dialog.cs
- Pinta/Actions/Addins/AddinManagerAction.cs
- Pinta/Actions/Help/AboutDialogAction.cs
- Pinta/Actions/Layers/RotateZoomLayerAction.cs
- Pinta/Dialogs/ErrorDialog.cs
Some were not. For example, `CloseAllDocumentsAction.Activated` invokes the `Activate` method — which doesn't provide a task to await, and relies on its state after it's executed — directly. Clearly, handlers like these need further thought.
In the second commit, I removed the `dispose` parameter in dialog extension methods and removed one of them that had 0 references. I think that mixing declarations with and without `using` could be confusing, and it also makes it very easy to `Dispose()` of the window before calling `Destroy()`. Perhaps, if the argument is re-added in the future, it should mean to `Destroy()` _and_ `Dispose()` the dialog.
> More action handlers that use dialogs were made `async`

- Pinta.Core/Classes/Document.cs
- Pinta.Core/Classes/DocumentHistory.cs
- Pinta.Core/Classes/DocumentWorkspace.cs
- Pinta.Core/ImageFormats/GdkPixbufFormat.cs
- Pinta.Core/ImageFormats/OraFormat.cs
- Pinta.Core/Managers/WorkspaceManager.cs
This comes at the cost of introducing `PintaCore` references into `GdkPixbufFormat` and `OraFormat`, but they should be easy to remove from there once the refactoring of the services is complete
> Removed `PintaCore` references from `Document`, `DocumentWorkspace`, and `DocumentHistory`

- Pinta.Core/Effects/BaseEffect.cs
All of its functionality can be accessed through the workspace and chrome services.
This also eliminates references to `PintaCore` in `BaseEffect`.
> Removed unused method in `BaseEffect`

- Pinta.Core/Extensions/Gtk/BoxStyle.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.Widget.cs
- Pinta.Core/Extensions/Gtk/StackStyle.cs
- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
- Pinta.Effects/Dialogs/Effects.PosterizeDialog.cs
- Pinta.Gui.Addins/AddinInfoView.cs
- Pinta/Dialogs/NewImageDialog.cs
For a conservative version of these changes (only a `Stack` method, and all other configuration being applied later, separately), look at the first commit only.
For a more 'daring' version (an extra argument of a custom type, for configurong the style), look at the combined diff.
> Added utility methods to easily create stacks of widgets

- Pinta.Core/Extensions/Gtk/GtkExtensions.Application.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.Data.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.External.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.Interaction.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.cs
- Pinta.Core/Extensions/OtherExtensions.cs
- Pinta.Gui.Widgets/Widgets/AnglePickerGraphic.cs
- Pinta.Gui.Widgets/Widgets/PointPickerGraphic.cs
- Pinta.Gui.Widgets/Widgets/StatusBarColorPaletteWidget.cs
To have the 'leading' file `GtkExtensions.cs` be as barebones as possible, and to more closely mirror what happens in `CairoExtensions`
> Categorized more methods in `GtkExtensions`

- Pinta.Core/Classes/AsyncEffectRenderer.cs
- Pinta.Core/Managers/LivePreviewManager.cs
The callback mess was untangled and the code is now sequential and easier to follow.
Next, we might want to address the `Update` event and then actually create a `RenderHandle` class, as discussed in https://github.com/PintaProject/Pinta/pull/1009#issuecomment-2384659481, but that's a topic for a future pull request. I already tinkered with it, and it is less straightforward than it appears to be due to `EffectData_PropertyChanged`, which I think has to be moved out of `LivePreviewManager`, and its `Start` method needs to be able to be canceled externally through a `CancellationToken` passed as an argument.
> Removed `Completed` event from `AsyncEffectRenderer`

- Pinta.Effects/Dialogs/Effects.AlignmentDialog.cs
- Pinta/Actions/View/EditCanvasGridAction.cs
- Pinta/Dialogs/CanvasGridSettingsDialog.cs
The changes to `EditCanvasGridAction`, specifically, are a demonstration that will help us start discussing a point.
I wanted to change some code in `StatusBarColorPaletteWidget` and `NewDocumentAction` so that their dialog code uses `async` and `await`. However, doing it the way I'm doing it with other dialogs means that I would be accessing its properties after it has been `Destroy`ed. That would work because the properties are custom, from the Pinta codebase, and in no way tied to the lifetime of the Gtk dialog in question. However, it doesn't feel that clean.
If we just need to read the values, I was thinking we could create specialized extension methods and using them instead of the generic dialog methods, something like:
```csharp
public static Task<NewImageInfo?> RunAsync (this …
```
> Tidying some dialog-related code

- readme.md
Also slightly change the format of some items in the Getting help / contributing
> Point to Github Discussions instead of Google Group for techical help

- Pinta.Core/Extensions/ToolBoxButton.cs
All widgets are visible by default and Show is also deprecated
> Remove unneeded call

- Pinta.Gui.Widgets/Widgets/ToolBoxWidget.cs
The style class does nothing in this case.
The height request is also useless for the toolbox. There should be some height request some ware to allow the history undo and redo buttons to be always visible, but this is probably not the best place and is also insufficient.
> Remove useless code

- Pinta.Core/Extensions/ToolBoxButton.cs
- Pinta.Gui.Widgets/Widgets/ToolBoxWidget.cs
Related discussion #1365
In summary, I believe that there's no practical benefit of the current behaviour which allows for a single vertical toolbar, if the expense is that the toolbar itself begins to shrink too.
Based on the following scales below, I'd like to imagine that this change is an overall win, since having personally tested before and after this patch being applied, the overall space used ends up being about the same; but on larger monitors, there's less mouse movement as well as bigger icons.
Smallest possible window size in Windows:
Arbitrarily larger:
Larger still
Full screen 1440p 100% display scaling
> ToolBoxWidget: Improve high DPI scenarios and improve layout flow.

- Pinta.Core/Classes/IExtension.cs
- Pinta.Core/PintaCore.cs
This allows us to specify an older Pinta version that add-ins are still compatible with
Fixes: #1379
> Configure the compatibility version for addins

- Pinta.Core/Managers/EffectsManager.cs
- Pinta.Effects/CoreEffectsExtension.cs
Also:
- Dictionary key type for registrations was changed from `BaseEffect` to `Type`, which allows for simple lookup instead of having to perform linear search (i.e. iterate all keys unnecessarily)
- Added checks to prevent double registration of effect of the same type.
> Made effect registration generic

- Pinta.Core/Managers/ChromeManager.cs
- Pinta.Core/Managers/LivePreviewManager.cs
- Pinta/Dialogs/ProgressDialog.cs
If we read the implementation of the progress dialog, we'd see there is a delay of 500 milliseconds inside the `Show` method. I am not sure why the delay is there, and in any case I think it should be handled externally; not by the dialog itself.
In the first commit I moved the handling of the delay outside of the dialog class, to the `LivePreviewManager`.
In the second commit I removed the delay entirely.
The overall diff makes it appear as if the `LivePreviewManager` didn't change, and in fact that is the combined result of the two commits, but by looking at each of them separately, what happened will become clearer.
> Simplified display of progress dialog

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
- Pinta.Gui.Widgets/Widgets/PaletteWidget.cs
- Pinta.Gui.Widgets/Widgets/StatusBarColorPaletteWidget.cs
- Pinta.Gui.Widgets/Widgets/Swatches.cs
- Pinta/MainWindow.cs
I had to temporarily move some utility methods (also used by `ColorPickerDialog`) to a new class, because the resulting code after removing `PintaCore` was a little awkward.
> Removed `PintaCore` references from `StatusBarColorPaletteWidget`

- Directory.Build.props
- Directory.Packages.props
- Pinta.Core/Pinta.Core.csproj
- Pinta.Docking/Pinta.Docking.csproj
- Pinta.Gui.Addins/Pinta.Gui.Addins.csproj
- Pinta.Gui.Widgets/Pinta.Gui.Widgets.csproj
- Pinta.Resources/Pinta.Resources.csproj
- Pinta.sln
- Pinta/Pinta.csproj
- properties/ReferenceGirCoreAdw1.props
- properties/ReferenceGirCoreGObject20Integration.props
- properties/ReferenceGirCoreGtk40.props
- properties/ReferenceGirCorePangoCairo10.props
To enable easy debugging of GirCore libraries, the msbuild property "GirCoreSource" can be set to a path where the GirCore source is located.
If this property is set the GirCore package references will be replaced by project references which point to the local GirCore source.
> Build: Support referencing GirCore via project reference

- Pinta.Docking/DockNotebook.cs
- Pinta.Gui.Addins/AddinInfoView.cs
- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
- Pinta.Tools/Tools/TextTool.cs
- Pinta/Dialogs/NewImageDialog.cs
This can generally be replaced by using the `Notify` method on the property definition, which avoids comparing against the string property name and also avoids running the event handler for every property change on the object
> Eliminate use of the OnNotify event

- Pinta.Core/Classes/Palette.cs
- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
- Pinta.Gui.Widgets/Widgets/PaletteWidget.cs
- Pinta.Gui.Widgets/Widgets/StatusBarColorPaletteWidget.cs
- Pinta/Actions/Edit/ResizePaletteAction.cs
I was thinking of being able to use the current palette for the dithering effect. To make that possible we have to be able to enumerate the colors in the palette.
Perhaps designing the class in a different way (from scratch) would be cleaner, but I think this will do for now.
> Colors in `Palette` exposed as `ReadOnlyCollection`

- Pinta.Gui.Widgets/Widgets/AnglePickerWidget.cs
Fixes #1142
The only catch that I see is that the range _includes_ 360 itself. It's annoying but not a huge problem, because the `Value` exposed by the widget is always a valid angle.
I think (but I'm not sure) that the value of 360 could be excluded through coercion by creating the `Gtk.SpinButton` with a `Gtk.Adjustment` and playing a bit with its `OnValueChanged` signal.
> Numeric spin in angle picker now wraps around

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
This avoids assertions when running a debug build of gir.core
Bug: #1340
> Avoid calling Unnotify again after removing the signal handler

- CHANGELOG.md
- Pinta.Resources/Icons.cs
- Pinta/MainWindow.cs
Creates a separate button for the View menu, making it easier to access (when compared to the current hamburger submenu solution). Doesn't change behavior when using the menubar.
Used the icon 'view-reveal-symbolic'. Not sure if it's always bundled with GTK/LibAdwaita or if it's a system icon that might cause problems on Windows/MacOS builds (if so, help needed here).
Part of #1428.
> [GUI] Move "View" menu out of the hamburger menu

- Pinta.Core/Actions/Command.cs
- Pinta.Core/Actions/FileActions.cs
- Event handlers didn't have the `event` keyword, so it was added
- Some properties didn't need setters, so they were removed or changed
> Refactored `Command`

- Pinta.Core/Managers/SystemManager.cs
This broke with #622 which changed the directory layout for the installer.
Bug: #1473
> Fix the data root directory for installed Windows builds

- Pinta.Core/Classes/DocumentWorkspace.cs
- Pinta.Core/Classes/Rectangle.cs
- Pinta.Core/Extensions/Cairo/CairoExtensions.Geometry.cs
- Pinta.Tools/Tools/CloneStampTool.cs
- Pinta.Tools/Tools/EraserTool.cs
- Pinta.Tools/Tools/PencilTool.cs
- Pinta.Tools/Tools/RecolorTool.cs
- Pinta.Tools/Tools/SelectTool.cs
- Pinta.Tools/Tools/ZoomTool.cs
- tests/Pinta.Core.Tests/RectangleTests.cs
The two methods previously had inconsistent naming from each other, and are reasonable constructors to have built-in.
This was part of the https://github.com/PintaProject/Pinta/tree/feature/resize-selected-pixels branch which I'm attempting to resurrect and split into smaller PRs
> Move methods for creating rectangles from a pair of points into the RectangleD / RectangleI classes

- Pinta.Core/Classes/Rectangle.cs
- Pinta.Tools/Handles/RectangleHandle.cs
- Pinta.Tools/Tools/SelectTool.cs
- tests/Pinta.Core.Tests/RectangleTests.cs
- The goal is to allow this to be used in the Move Selected Pixels tool for scaling the selection in a more intuitive manner
- The Select tool's behaviour should be unchanged, except for one minor difference. If the rectangle is inverted (e.g. dragging the bottom right corner before the top left corner), after a mouse up the rectangle resets itself to no longer be inverted so that the mouse cursors for each handle point in the expected direction
- Add an option to `RectangleD.FromPoints()` to control the behaviour when the end point is before the start point. This can be clamped to a zero size rectangle (which will be used for the transform tools) rather than inverting the rectangle
Bug: #585
> Add a new RectangleHandle control, extracted from the selection tool

- installer/windows/bundle_gtk.targets
These are new dlls required by the latest GTK dependencies
> Fix missing dlls from the Windows installer

- Pinta.Docking/DockPanel.cs
Fixes https://github.com/PintaProject/Pinta/issues/1472
After minimizing a panel in a vertical stack, the remaining pane wouldn’t expand correctly. The fix sets ResizeStartChild to true when maximizing and clears the PositionSet flag when minimizing.
- Allow the first pane in a stack to resize by enabling ResizeStartChild during maximize
- Clear the pane’s stored divider position on minimize to let the remaining panel fill the space
> Resize panel to full size on Maximize

- Pinta/AddinSetupService.cs
Some internal code in Mono.Addins assumes the header's ContentLength property is never null, but this is not the case for gzipped responses from Github's server. This started happening recently so it may have been a change on Github's end. The workaround is to register our own HttpClient provider which disables gzip compression in our requests.
Fixes: #1542
> Work around a bug in Mono.Addins which could fail to fetch the add-in repository

- Pinta.Core/Effects/GradientRenderer.cs
- Pinta.Core/Effects/GradientRenderers.cs
The gradient renderers can just interpolate to the end color when the two points are equal, rather than having a special case for filling in the end color (which duplicates some of the color blending logic)
Bug: #1543
> Simplify the gradient renderer to reduce special cases

- Pinta.Core/Effects/GradientRenderer.cs
- Pinta.Tools/Tools/GradientTool.cs
- The start and end colors should have premultiplied alpha since they are used when modifying the image surface's data directly (see `GradientRenderer.ProcessGradientLine()`)
- Replace `ColorBgra.Blend()` with `ColorBgra.Lerp()` for premultiplied alpha (see #1546)
Fixes: #1543
> Fix the gradient renderer's use of straight vs premultiplied alpha

- CHANGELOG.md
- Pinta.Core/Classes/SettingNames.cs
- Pinta.Core/Managers/CanvasGridManager.cs
- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
- Pinta.Tools/Handles/RectangleHandle.cs
- Pinta/ActionHandlers.cs
- Pinta/Actions/View/EditCanvasGridAction.cs
- Pinta/Dialogs/CanvasGridSettingsDialog.cs
- tests/Pinta.Core.Tests/FileFormatTests.cs
- tests/Pinta.Core.Tests/OtherExtensionsTest.cs
- tests/Pinta.Core.Tests/ScanlineTest.cs
Implements #1438. Does not implement color and angle changes (fixed #000 and 45deg). Does implement size, though.
Please squash the commits.
> Adds axonometric grid

- Pinta.Core/Classes/Color/ColorBgra.Blending.cs
- Pinta.Core/Classes/Color/ColorBgra.cs
- Pinta.Core/Classes/ColorGradient.cs
- Pinta.Core/Classes/IColor.cs
- Pinta.Core/Extensions/Cairo/CairoExtensions.ColorType.cs
- Pinta.Effects/Effects/CloudsEffect.cs
- Pinta.Effects/Effects/GradientHelper.cs
- Pinta.Effects/Effects/JuliaFractalEffect.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
- Pinta.Gui.Widgets/Widgets/ColorPickerSlider.cs
- tests/Pinta.Effects.Tests/GradientTests.cs
This requires making `ColorGradient` generic, otherwise there would be lots of unnecessary conversions
>  Modified `ColorPickerSlider.DrawGradient` to use proper gradient 

- Pinta.Core/Actions/WindowActions.cs
- Pinta.Core/Managers/ActionManager.cs
- Pinta.Core/Managers/ToolManager.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta/Actions/Edit/PasteIntoNewImageAction.cs
- Pinta/Actions/File/CloseDocumentAction.cs
- Pinta/Actions/File/NewDocumentAction.cs
- Pinta/Actions/Window/SaveAllDocumentsAction.cs
- Pinta/Main.cs
- Pinta/MainWindow.cs
`SetAccelsForAction()` is quite expensive (I suspect it needs to go through and update any widgets which might be using the action), so this should be done once up front rather than when rebuilding the menu.
This improves the performance of opening 20 documents at once from 17s to 400ms
Bug: #1574
> Fix performance issues when opening many documents

- Pinta.Core/Algorithms/Utility.cs
- Pinta.Core/Classes/Angle.cs
- Pinta.Effects/Effects/DentsEffect.cs
- Pinta.Effects/Effects/FragmentEffect.cs
It exposes _static_ information about the angle type. Conversions between types should still be explicit
Also, removed the `<` and `>` operators because they aren't used and they could be confusing (for instance, an angle of 370 degrees would be less than an angle of 20 degrees)
Related to the above, I'm thinking that the `+` and `-` operators could be confusing, too, or at least misleading. Perhaps their signature shouldn't be `(TAngle a, TAngle b)`, but `(TAngle a, double b)`. But I need to think about it, and feedback on this idea would be helpful, too.
> Created `IAngle` interface

- Pinta.Core/Classes/Document.cs
- Pinta.Core/Classes/DocumentSelection.cs
- Pinta.Core/Extensions/Cairo/CairoExtensions.Core.cs
- Pinta.Core/Extensions/Cairo/CairoExtensions.Geometry.cs
- Pinta.Core/Managers/LivePreviewManager.cs
- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
- Pinta.Tools/Tools/MoveSelectedTool.cs
- Pinta.Tools/Tools/MoveSelectionTool.cs
- Pinta/MainWindow.cs
This tidies up some minor issues before making further changes in PR #1515
- Remove the reference to the owning document. This was only used for creating a Cairo.Context for building the selection path, but this doesn't actually need access to the document's active layer. Instead, a new utility method provides a context which can be used solely for building paths
- Use `DocumentSelection.Bounds()` to get the selection bounds, rather than going through the Cairo.Path. This also makes the GetBounds() extension method unused, eliminating some references to the global PintaCore
- Remove unused Path.Clone() extension method
> Refactor DocumentSelection

- Pinta.Core/Classes/AsyncEffectRenderer.cs
- Pinta.Core/Classes/RenderHandle.cs
- Pinta.Core/Managers/LivePreviewManager.cs
All state consists of local variables in the `Start` method, accessible from local functions, too, but not being exposed to the outside, except in a controlled way, through the `RenderHandle` object that is being returned.
Further refactoring is needed, but it's getting closer to what was discussed in https://github.com/PintaProject/Pinta/pull/1009#issuecomment-2384659481 :)
> No state is saved in `AsyncEffectRenderer` anymore

- Pinta.Gui.Widgets/Widgets/Layers/LayersListView.cs
Previously the selected list item wasn't updated after loading a new document into the panel, so the top-most layer was shown as selected by default. This could cause very confusing behaviour, as in bug #1573, if a different layer was actually the current layer internally
Bug: #1573
> Update the layer widget's selection when the active document switches

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
The `get`ter of `CurrentColor` was changed so that code inside the constructor would depend less on the state of the object (which hasn't been properly initialized). This made it possible to move the assignment to the `Colors` property all the way to the end of the constructor
> Refactoring in `ColorPickerDialog`

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
- Pinta.Gui.Widgets/Widgets/StatusBarColorPaletteWidget.cs
Not only is it clearer, but I think it's necessary for implementing #1611 with Pinta's color picker dialog
> Changed parameter for constructor of `ColorPickerDialog`

- Pinta.Core/Classes/Color/ColorBgra.Conversion.cs
- Pinta.Core/Managers/PaletteManager.cs
- tests/Pinta.Core.Tests/ColorTests.cs
- Remove the `ColorBgra` hex conversion methods in favour of the ones in `Cairo.Color`. In the palette manager this was a source of conversions between ColorBgra and Cairo.Color which didn't convert between premultiplied alpha, which we want to eliminate for bug #1553. There was also no need for having duplicate logic for this in different color types
- Since `ColorBgra.TohexString()` didn't produce a hex string in RGBA order, we need some simple wrappers to reorder the color channels. This preserves compatibility when loading existing settings from disk
- Fix the `Cairo.Color` tests to include alpha when parsing hex strings, and add tests for converting to hex
> Consolidate methods for converting colors to/from hex strings

- Pinta.Effects/Effects/AddNoiseEffect.cs
- Pinta.Effects/Effects/CellsEffect.cs
- Pinta.Effects/Effects/DentsEffect.cs
- Pinta.Effects/Effects/JuliaFractalEffect.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
- Pinta.Effects/Effects/PolarInversionEffect.cs
The default increment, 0.01, is too small for certain parameters, making the arrow buttons annoying to use.
As a thought, would it be a good idea to allow the user to configure the increment size, or would that complicate the user interface too much?
> Specified increment size in several `double`-typed effect configuration parameters

- Pinta.Effects/Effects/JuliaFractalEffect.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
The message for the second commit is wrong. It should be 'Mandelbrot fractal'.
These are the low-hanging fruits. There are many other effects (for example `OilPaintingEffect` and `GaussianBlurEffect`, among others) which are good candidates for this type of refactoring, but require a more thoughtful approach (perhaps by creating some `BgraAggregation` type? this has the added marginal benefit of requiring less space on the stack)
> Refactored several effects to use the `ColorBgra.Blend` method

- installer/macos/build_installer.sh
- This is something we should likely have been doing anyways to reduce file accesses on startup. I'm not sure if it will have any impact on the issue with icon loading errors for arm64 though
- Also regenerate the Adwaita icon theme cache for good measure. This probably isn't necessary, but if we want to trim unused icons in the future we would need to regenerate the cache anyways
Bug: #1605
> macOS: generate an icon theme cache for our custom icons

- Pinta.Core/Actions/ViewActions.cs
- Pinta.Core/Managers/ActionManager.cs
Fixes https://github.com/PintaProject/Pinta/issues/1429
Both cursor position and selection rectangle size widgets and labels are now  left aligned with enough space for 12 characters so that coordinates in the tens of thousands can be displayed. 
The widgets can still overlap the color palette if the application window has a very narrow size, but that feels like a separate issue to address (maybe by imposing a minimum width for the application window) and it's not so bad now that the icons aren't jumping around anymore.
> Prevent cursor position and selection size widget icons from jumping around when the coordinates update

- Pinta.Core/Classes/Color/ColorBgra.Blending.cs
- Pinta.Core/Effects/GradientRenderer.cs
- Pinta.Core/Extensions/OtherExtensions.cs
- Pinta.Effects/Effects/FeatherEffect.cs
- Pinta.Effects/Effects/OutlineObjectEffect.cs
- Pinta.Gui.Widgets/Widgets/HistogramWidget.cs
- tests/Pinta.Core.Tests/ColorBgraTests.cs
Also fixed some surrounding code which was not using premultiplied alpha
Bug: #1553
> Port ColorBgra.NewAlpha() to work with premultiplied alpha

- Pinta.Core/Classes/Palette.cs
- Pinta.Core/Extensions/PaletteHelper.cs
- Pinta.Core/Managers/PaletteManager.cs
At present the `Palette` class is doing too much, including loading colors from files, which could be handled externally.
As an idea for the future, we could get rid of the `Palette` class and create a general-purpose `NotifyingCollection<T>` that allows us to listen to several events like `ItemChanged`, `ItemsReplaced`, `CollectionCleared` (which shouldn't necessarily be separate `event`s, but we could know which kind of event it was through pattern matching)
> Moved some methods from `Palette` to new `PaletteHelper` class

- CHANGELOG.md
- Pinta.Core/Managers/EffectsManager.cs
Since the API was broken in #1665, this could be the best moment to do something like this.
> Removing legacy methods from `EffectsManager`

- Pinta.Tools/Tools/TextTool.cs
Currently, CTRL+A selects text from the beginning of the current line until the end. Now the complete text gets selected.
> Fix select-all-text (CTRL+A)

- Pinta.Effects/Effects/PolarInversionEffect.cs
this also reduces the casting that happens through accesses to the `Data` property.
> `InverseTransform` method in `PolarInversionEffect` was made local

- .github/workflows/build.yml
- Pinta.Core/Managers/SystemManager.cs
- installer/windows/bundle_gtk.targets
- installer/windows/installer.iss
- readme.md
- Switch to using the `clang64` environment for x86_64 systems (previously we used the `mingw64` environment). For ARM we need to use the `clangarm64` environment, so this makes it easier to maintain the packaging scripts for both systems since the C++ runtime dlls, etc are consistent
- Fix errors with loading icons in local development builds on Windows, noticed while testing this out
Fixes: #1378
> Add ARM64 installer for Windows

- .github/workflows/build.yml
- These can be set up as a matrix since nearly all the steps are the same
- Also bump the Linux build to the latest default runner
> CI: consolidate logic for arm64 and intel mac builds

- Pinta.Core/Classes/DocumentSelection.cs
- Pinta.Core/Extensions/Cairo/CairoExtensions.Geometry.cs
- Pinta.Tools/Tools/SelectTool.cs
- Store a rectangle rather than separate origin / end points. This is simpler, and for PR #1515 this will likely be extended further to also store an orientation
- Clarify that the bounds are only used for interactive manipulation by tools, and might not reflect the selection's entire bounds when e.g. using intersection modes
- Adjust the `TransformPoint()` signature to be easier to use
> Refactor how the DocumentSelection bounds are tracked

- Pinta.Tools/Tools/TextTool.cs
In https://github.com/PintaProject/Pinta/pull/1707 the TextTool cursor was fixed. However, the responsible function can be simplified further.
> refactor: Simplify TextTool - UpdateMouseCursor further

- Pinta.Core/Algorithms/BlendOpHelper.cs
- Pinta.Core/Effects/UserBlendOps.Multiply.cs
- Pinta.Core/Effects/UserBlendOps.Normal.cs
- Pinta.Core/Effects/UserBlendOps.Screen.cs
Two versions are provided.
- The first one is the 'vanilla' version
- The second one is a bit more clever, makes the code shorter I think it's probably more efficient once the generic types are instantiated, but it could also be trickier to understand
> Created and used helper for blend operations

- Pinta.Gui.Widgets/Widgets/Ruler.cs
There is a comment in the code:
```csharp
// TODO-GTK3 - cache the ticks
```
This is an attempt to do that with an `ImageSurface` that can be re-used, and is deleted when some property affecting the drawing of the ruler changes.
> Caching drawn ruler

- Pinta.Core/Classes/BitMask.cs
- Pinta.Core/Classes/Fraction.cs
- Pinta.Core/Classes/HsvColor.cs
- Pinta.Core/Classes/Re-editable/Text/TextPosition.cs
- Pinta.Core/Classes/Scanline.cs
With the `HashCode` utility we don't have to roll our own `GetHashCode` implementations if they are just a combination of their properties
> Improved implementation of `GetHashCode` in several classes

- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
- Pinta.Gui.Widgets/Widgets/PointPickerWidget.cs
To see the bug:
- Start Pinta
- Run the vignette effect. The point picker will have the coordinates of the center of the canvas
- Without changing anything, close the dialog
- Run the vignette effect again. The point picker will be at the bottom-right corner
With this change, the point will be where the user left it before closing it, with the only exception being (0, 0)
This new behavior is saner, but it could be inconsistent with the behavior of the offset picker, which always starts at the center when one opens the dialog (you can see it with, say, the zoom blur effect). I would like to make their behavior consistent, but I would leave that for a future pull request.
> Fixed bug in point picker for `PointI`

- Pinta.Tools/Handles/RectangleHandle.cs
- Before, due to numerical inaccuracy rectangles were not expanded uniformly but rather drifted to one side.
- improving readability of RectangleHandler by changing magic numbers to enum.
> Fix uniform expansion of rectangle shapes

- Pinta.Core/Managers/PaletteManager.cs
- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
- Pinta.Gui.Widgets/Widgets/PaletteWidget.cs
- Pinta.Gui.Widgets/Widgets/StatusBarColorPaletteWidget.cs
- tests/Pinta.Effects.Tests/Mocks/MockPalette.cs
- tests/PintaBenchmarks/Mocks/MockPalette.cs
The code corresponding to the feature can be examined in 4367073a92cc4e268bc66294538701096160c8af.
On the way I also changed `StatusBarColorPaletteWidget` (and related classes) to receive `IPaletteService` instead of `PaletteManager`.
I am selecting blue with an alpha of 128, and transparent. You can see the result by looking at the checkered spots:
Before this change these spots would have looked (in the case of dark mode) dark blue and very dark gray, like the background.
Note: ~You will notice that I'm not showing a screenshot of the old behavior. I simply can't start Pinta anymore.~ If I try to run `dotnet run --project Pinta` the command returns with no output. I had to use the cloud build in order to run my changes, and even then I had to try in another computer, because neither …
> Checkerboard background for clear visualization of palette colors with transparency

- Pinta.Gui.Widgets/Widgets/Canvas/CanvasWindow.cs
- Pinta.Gui.Widgets/Widgets/Ruler.cs
- In `RulerDrawSettings` the meaning of `Start` and `End` wasn't that clear, in my opinion, so I changed it to a range named `Ticks`
- The `Set-` methods were made `set`ters of their respective properties
> Ruler parameter bundling

- Pinta.Core/Extensions/Cairo/CairoExtensions.Samples.cs
- Pinta.Core/ImageFormats/GdkPixbufFormat.cs
- Pinta.Core/ImageFormats/JpegFormat.cs
This requires explicitly converting to a Gdk.Pixbuf which doesn't contain alpha.
Bug: #1774
> Work around errors saving JPEG files with the glycin pixbuf loader

- Pinta/Actions/File/NewDocumentAction.cs
- Pinta/Messages/ActionOptions.cs
This was a regression from 88489ead which accidentally saved the background color value in the settings, rather than the background type setting.
Fixes: #1788
> Fix errors from saving the new image background setting with inconsistent types

- Pinta.Tools/Handles/GradientHandle.cs
- Pinta.Tools/Handles/LineHandle.cs
- Pinta.Tools/HistoryItems/GradientHistoryItem.cs
- Pinta.Tools/Tools/GradientTool.cs
-  When creating a  gradient, one handle will appear where you clicked and a second handle will be dragged until the mouse button is released.
- When hovering the cursor over one of the handles, it will be highlighted and the cursor will change to a hand.
- When clicking (with any mouse button) on the handle and dragging, the handle will follow the cursor.
- Clicking on a point apart from any handle will create a new gradient.
- Pressing the enter key will finalize the gradient and remove the handles. So does `OnDeactivated` or `OnCommit`
- Creating, modifying or finalizing a gradient will add a new history item.
> Added handles for gradient tool (#1533)
