- Pinta.Core/Actions/ViewActions.cs
- Pinta.Docking/DockNotebook/DockNotebook.cs
- Pinta.Docking/DockNotebook/DockWindow.cs
- Pinta.Docking/DockNotebook/TabEventArgs.cs
- Pinta.Docking/DockNotebook/TabStrip.cs
- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
- Pinta/Actions/View/ImageTabsToggledAction.cs
- Pinta/DialogHandlers.cs
- Pinta/MainWindow.cs
- Pinta/Pads/ColorPalettePad.cs
- Pinta/Pads/HistoryPad.cs
- Pinta/Pads/LayersPad.cs
- Pinta/Pads/OpenImagesPad.cs
- Pinta/Pads/ToolBoxPad.cs
- Pinta/Pinta.csproj
This should be the last of implementing all the new docking features, allowing tabs to be docked side-by-side and in floating windows.
> Finish tab docking

- Pinta.Tools/Tools/EraserTool.cs
Added a combobox in the toolbar to change the type of the erase tool.
> Added smooth erase tool

- Pinta.Core/Effects/ColorBgra.cs
- Pinta.Effects/Effects/GaussianBlurEffect.cs
reason cairo images use premultipled alpha values
> GaussianBlurEffect.cs doesn't work correctly with alpha values != 255

- po/POTFILES.in
- xdg/Makefile.am
- xdg/pinta.appdata.xml.in
This will get you listed in Linux app stores. Compare https://people.freedesktop.org/~hughsient/appdata/
> Added a translateable Linux AppData file

- po/de.po
- po/en_GB.po
- po/messages.pot
A followup of https://github.com/PintaProject/Pinta/pull/121.
> Updated the translation file template.

- readme.md
the one linked before is gone. I took the current one from https://pinta-project.com/pintaproject/pinta/
> Fixed the link to the suggestions page.

- xdg/pinta.appdata.xml.in
I would like to enhance the AppData file.
This is related to submitting my flatpak package to the Flathub repository.
https://github.com/flathub/flathub/pull/756
It would be nice if the author decided to participate in the further development of this flatpak package.
> Enhance AppData file

- .gitignore
- Pinta.Core/Effects/Utility.cs
- Pinta.Tools/Tools/BaseTransformTool.cs
- Pinta.Tools/Tools/MoveSelectedTool.cs
- Pinta.Tools/Tools/MoveSelectionTool.cs
Added a step rotation for the base transform tool when the left shift key is pressed.
> Step rotate branch

- xdg/pinta.appdata.xml.in
Should probably be adjusted in other branches as well.
> Fix URLs in appdata.

- xdg/pinta.appdata.xml.in
Please always update release notes also in appdata file.
Taken from [here](https://github.com/flathub/com.github.PintaProject.Pinta/blob/51a00211ac74e607349459bdcba17b64b233eedf/pinta-appdata.patch).
@hfiguiere I committed your changes upstream.
> Add release notes for 1.7 to appdata.

- Pinta.Core/Classes/Palette.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta.Core/PaletteFormats/PaletteFormats.cs
> Crash on wrong file using Palette Tool

- Pinta.Gui.Widgets/Widgets/Layers/LayersListWidget.cs
There are a couple of bugs when switching between layers:
Bug 1
- Create new image
- Click add new layer
- Click Background layer
- Click Layer 2
Bug 2
- Create new image
- Click add new layer
- Click checkbox to make Layer 2 hidden
- Click checkbox to make Background layer hidden
- Click checkbox to make Layer 2 visible
Both result in the layer list being duplicated.  Performing more switching will cause the list to get even more out of sync until you get a native error about accessing protected memory.
This seems to be caused by a change in `TreeStore.Clear ()` in GTK3.  Previously calling this did not trigger `TreeView.CursorChanged`, but now it does.  This causes us to call `Reset ()` multiple times recursively which wreaks havoc.
The fix is to create an `updating_model` flag to …
> Fix bug when switching between layers.

- CHANGELOG.md
- Pinta.Core/Managers/ToolManager.cs
Implement click and drag with the middle mouse button to pan the current image.
https://communiroo.com/PintaProject/pinta/suggestions/419
> Implement middle click and drag to pan.

- Pinta.Core/Classes/BaseTool.cs
- Pinta.Core/Classes/SelectionModeHandler.cs
- Pinta.Core/Managers/SettingsManager.cs
- Pinta.Core/PintaCore.cs
- Pinta.Core/Widgets/ToolBarDropDownButton.cs
- Pinta.Tools/Editable/EditEngines/ArrowedEditEngine.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Editable/EditEngines/RoundedLineEditEngine.cs
- Pinta.Tools/Tools/BaseBrushTool.cs
- Pinta.Tools/Tools/ColorPickerTool.cs
- Pinta.Tools/Tools/EraserTool.cs
- Pinta.Tools/Tools/FloodTool.cs
- Pinta.Tools/Tools/FreeformShapeTool.cs
- Pinta.Tools/Tools/GradientTool.cs
- Pinta.Tools/Tools/LassoSelectTool.cs
- Pinta.Tools/Tools/MagicWandTool.cs
- Pinta.Tools/Tools/PaintBrushTool.cs
- Pinta.Tools/Tools/RecolorTool.cs
- Pinta.Tools/Tools/SelectTool.cs
- Pinta.Tools/Tools/ShapeTool.cs
- Pinta.Tools/Tools/TextTool.cs
All tool settings are saved in the `settings.xml` file and retrieved on future runs to preserve the user's current state.
> Persist tool settings between application launches.

- Pinta.Gui.Widgets/Widgets/Ruler.cs
Draw ruler marker position guidelines.
> Ruler - Draw current mouse position marker.

- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
> Fix shape type not changing when there is no selected shape

- Pinta.Core/Classes/AsyncEffectRenderer.cs
- Pinta.Core/Extensions/GioStream.cs
- Pinta.Core/Managers/ChromeManager.cs
- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
- Pinta/Options.cs
Modified certain null checks to use the nameof() operator. No behavior has changed
> Small modernization of null checks

- Pinta.Effects/Adjustments/AutoLevelEffect.cs
- Pinta.Effects/Adjustments/BlackAndWhiteEffect.cs
- Pinta.Effects/Adjustments/BrightnessContrastEffect.cs
- Pinta.Effects/Adjustments/CurvesEffect.cs
- Pinta.Effects/Adjustments/HueSaturationEffect.cs
- Pinta.Effects/Adjustments/InvertColorsEffect.cs
- Pinta.Effects/Adjustments/LevelsEffect.cs
- Pinta.Effects/Adjustments/PosterizeEffect.cs
- Pinta.Effects/Adjustments/SepiaEffect.cs
- Pinta.Effects/CoreEffectsExtension.cs
- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
- Pinta.Effects/Effects/AddNoiseEffect.cs
- Pinta.Effects/Effects/CloudsEffect.cs
- Pinta.Effects/Effects/GaussianBlurEffect.cs
- Pinta.Effects/Effects/GlowEffect.cs
- Pinta.Effects/Effects/InkSketchEffect.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
- Pinta.Effects/Effects/PencilSketchEffect.cs
- Pinta.Effects/Effects/PolarInversionEffect.cs
- Pinta.Effects/Effects/RedEyeRemoveEffect.cs
- Pinta.Effects/Effects/SoftenPortraitEffect.cs
- Pinta.Effects/Effects/WarpEffect.cs
- Pinta.Effects/Utilities/EffectHelper.cs
As an extra, I removed unused namespace references in that same project
> Renamed private fields to follow naming conventions in `Pinta.Effects`

- Pinta.Core/Effects/BaseEffect.cs
- Pinta.Core/Effects/GradientRenderer.cs
- Pinta.Core/Effects/Histogram.cs
- Pinta.Core/Effects/Scanline.cs
...not all, as I don't want to create conflicts with other open pull requests, and in any case it's easier to review changes when they are not too many
> Modernized the syntax of getters in a few places

- Pinta.Core/Effects/BitMask.cs
- tests/Pinta.Core.Tests/BitMaskTest.cs
...And added tests to that effect
> Made `BitMask` reject negative indexing

- tests/Pinta.Core.Tests/ScanlineTest.cs
The original pull request is #287 , but rebasing my branch onto `master` messed it up, so I'm re-opening it here.
I think it's good for merging as is, and I could improve it in a future pull request.
> Added tests for `Scanline`

- Pinta.Tools/Tools/EllipseSelectTool.cs
The file is small and simple enough that there should be no problems
> File-scoped namespace for `EllipseSelectTool.cs`

- Pinta.Tools/Brushes/CircleBrush.cs
- Pinta.Tools/Brushes/GridBrush.cs
- Pinta.Tools/Brushes/PlainBrush.cs
- Pinta.Tools/Brushes/SplatterBrush.cs
- Pinta.Tools/Brushes/SquaresBrush.cs
Their functionality is stable enough and the files small enough that there should be no problem.
> File-scoped namespaces for brushes

- Pinta.Tools/Tools/PanTool.cs
The file is small and simple enough that there should be no problems
**Also**, inverted `if` logic in `OnMouseMove`
> File-scoped namespace for `PanTool.cs`

- Pinta.Tools/Editable/EditEngines/EllipseEditEngine.cs
- Pinta.Tools/Editable/EditEngines/LineCurveEditEngine.cs
- Pinta.Tools/Editable/EditEngines/RectangleEditEngine.cs
The files are small and simple enough that there should be no problems
> File-scoped namespaces for several edit engines

- Pinta.Core/Actions/Command.cs
- Pinta.Core/Actions/ViewActions.cs
- Pinta.Core/Classes/Document.cs
- Pinta.Core/Classes/DocumentSelection.cs
- Pinta.Core/Classes/DocumentWorkspace.cs
- Pinta.Core/Classes/Layer.cs
- Pinta.Core/Classes/Palette.cs
- Pinta.Core/Classes/Re-editable/ReEditableLayer.cs
- Pinta.Core/Classes/Re-editable/Text/TextLayout.cs
- Pinta.Core/Classes/Re-editable/Text/TextPosition.cs
- Pinta.Core/Effects/Histogram.cs
- Pinta.Core/Effects/UnaryPixelOps.cs
- Pinta.Core/Extensions/GioStream.cs
- Pinta.Core/Managers/ChromeManager.cs
- Pinta.Core/Managers/RecentFileManager.cs
- Pinta.Effects/Adjustments/BrightnessContrastEffect.cs
- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
- Pinta.Gui.Widgets/Widgets/PointPickerWidget.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Tools/TextTool.cs
- Pinta/Actions/File/DBus/ScreenshotPortal.cs
- Pinta/Dialogs/ProgressDialog.cs
- Pinta/Options.cs
Done automatically by IDE.
For when a getter or setter consists of a single expression or statement
> Modernized remaining getters/setters

- Pinta.Core/HistoryItems/AddLayerHistoryItem.cs
- Pinta.Core/HistoryItems/DeleteLayerHistoryItem.cs
- Pinta.Core/HistoryItems/FinishPixelsHistoryItem.cs
- Pinta.Core/HistoryItems/InvertHistoryItem.cs
- Pinta.Core/HistoryItems/MovePixelsHistoryItem.cs
- Pinta.Core/HistoryItems/PasteHistoryItem.cs
- Pinta.Core/HistoryItems/ResizeHistoryItem.cs
- Pinta.Core/HistoryItems/SelectionHistoryItem.cs
- Pinta.Core/HistoryItems/SimpleHistoryItem.cs
- Pinta.Core/HistoryItems/SwapLayersHistoryItem.cs
- Pinta.Core/HistoryItems/TextHistoryItem.cs
- Pinta.Core/HistoryItems/UpdateLayerPropertiesHistoryItem.cs
Except those which are actually inherited from
> Sealed most history item classes

- Pinta.Tools/Editable/Shapes/LineCurveSeriesEngine.cs
- `GenerateCubicBezierCurvePoints` is now a generator (returns `IEnumerable<>` and uses `yield return`) instead of returning a `List<>`
- Reduced nesting by one level in `GeneratePoints`
> Simple refactorings of `LineCurveSeriesEngine`

- Pinta.Core/Classes/Re-editable/Text/TextEngine.cs
- Pinta.Core/Extensions/CairoExtensions.cs
These conflicted with a previous pull request, but it's merged now
> Yet more objects are created using block initialization

- Pinta/MacInterop/ApplicationEvents.cs
Also, as an extra, sealed exception classes
> Fixed naming violation in `ApplicationEvents`

- Pinta.Effects/Effects/CloudsEffect.cs
...Also, fixed some naming violations
> Fixed formatting of array initialization in `CloudsEffect`

- Pinta.Effects/Effects/GaussianBlurEffect.cs
Also, made return value of `CreateGaussianBlurRow` to be `ImmutableArray`
> Reduced nesting levels in `GaussianBlurEffect` through `if` inversion

- Pinta.Effects/Effects/ReliefEffect.cs
It was originally a getter, but I don't think any member that performs so many calculations should be a getter
> `ReliefEffect.Weights` was converted to a method

- Pinta.Effects/Effects/EmbossEffect.cs
It performs so many computations that it should hardly be considered a property
> Converted `EmbossEffect.Weights` to method

- Pinta.Core/Classes/Point.cs
Methods in that class (and in that file) are extremely simple
> Used expression body for methods in `PointD`

- Pinta.Effects/Effects/AddNoiseEffect.cs
To achieve that, it needed to be made into the return value of a static method instead of being assigned inside it
> Made `AddNoiseEffect.lookup` `readonly`

- Pinta.Core/Classes/Re-editable/Text/TextEngine.cs
- Pinta.Core/ImageFormats/OraFormat.cs
- Pinta.Docking/DockPanel.cs
- Pinta.Effects/Effects/PixelateEffect.cs
- Pinta.Tools/Tools/TextTool.cs
- Pinta/Actions/File/SaveDocumentImplementationAction.cs
This is a chain reaction from #275
> `private` methods that don't access any instance members were made `static`

- Pinta.Core/PaletteFormats/GimpPalette.cs
- Pinta.Core/PaletteFormats/IPaletteSaver.cs
- Pinta.Core/PaletteFormats/PaintDotNetPalette.cs
- Pinta.Core/PaletteFormats/PaintShopProPalette.cs
Instead of the previous `List<Color>`
> Changed signature of `IPaletteSaver.Save` to accept `IReadOnlyList<Color>`

- Pinta.Core/Classes/Re-editable/Text/TextLayout.cs
Originally opened in #418 , but rebase messed up the diff
> Optimized `TextLayout.GetSelectionRectangles`

- Pinta.Effects/Effects/CloudsEffect.cs
In response to
https://github.com/PintaProject/Pinta/pull/429#discussion_r1299277725
> Assigned `Count` to immutable array builder in `CloudsEffect`

- Pinta/Dialogs/LayerPropertiesDialog.cs
I'm not sure why there is a separate `Build()` method
> In `LayerPropertiesDialog`, moved body of `Build()` to constructor

- Pinta.Core/Effects/UserBlendOps.Generated.cs
Despite its name, I guess that this file is not going to be overwritten by an automated tool. I'm seeing that it has many comments written by humans
> Modernized getter syntax in `UserBlendOps.Generated.cs`

- Pinta.Core/Actions/AppActions.cs
- Pinta.Core/Actions/FileActions.cs
- Pinta.Core/Classes/Document.cs
- Pinta.Core/Classes/DocumentWorkspace.cs
- Pinta.Core/Classes/ObservableObject.cs
- Pinta.Core/Classes/Palette.cs
- Pinta.Core/Classes/Re-editable/Text/TextEngine.cs
- Pinta.Core/Effects/Histogram.cs
- Pinta.Core/Managers/ChromeManager.cs
- Pinta.Core/Managers/LivePreviewManager.cs
- Pinta.Core/Managers/PaintBrushManager.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta.Core/Widgets/ToolBarDropDownButton.cs
- Pinta.Gui.Widgets/Widgets/PointPickerGraphic.cs
I don't know why these invocations weren't caught in the previous code analysis
> Simplified more delegate invocations

- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
Along the way I made some minor modifications like removing an unnecessary namespace reference and removing a bit of clutter in the code
> Modernized delegate syntax in `PintaCanvas`

- Pinta.Tools/Dashes/DashPatternBox.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Editable/EditEngines/EllipseEditEngine.cs
- Pinta.Tools/Editable/EditEngines/LineCurveEditEngine.cs
- Pinta.Tools/Editable/EditEngines/RectangleEditEngine.cs
- Pinta.Tools/Editable/EditEngines/RoundedLineEditEngine.cs
- Pinta.Tools/Tools/FreeformShapeTool.cs
...This makes it clearer that it can't be modified from the outside
> `DashPatternBox.ComboBox` was turned into a property

- Pinta.Core/Managers/LivePreviewManager.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Tools/TextTool.cs
Instead of using an `if` block
> Used null propagation for invoking a method of object that we aren't certain is not `null`

- Pinta.Tools/Editable/EditEngines/RoundedLineEditEngine.cs
Also, made the code more compact on the way by deleting blank lines in several places
> Reduced nesting through if inversion in `RoundedLineEditEngine`

- Pinta.Core/Managers/PaletteManager.cs
Also, shortened getter syntax on the way
> Reduced nesting level through `if` inversion in `PaletteManager.DoKeyPress`

- Pinta.Core/Classes/Point.cs
- Pinta.Tools/Brushes/CircleBrush.cs
- Pinta.Tools/Brushes/GridBrush.cs
- Pinta.Tools/Brushes/SplatterBrush.cs
- Pinta.Tools/Brushes/SquaresBrush.cs
I also added a `Magnitude` method to `PointI`, but is that a good idea (given that the return type is `double` even though the structure is `int`-based)? If not, I'll stick with the inline calculation
> Grouped variables in a few brush classes using `PointI` and `PointD`

- Pinta.Effects/Effects/TwistEffect.cs
It's hard to show all the refactoring process, but. You can see that the respective test still passes :)
> Separated `TwistEffect.Render` into several methods

- Pinta.Core/Classes/SelectionModeHandler.cs
Also, `DetermineCombineMode` now returns values directly instead of assigning to a variable first
> Extracted code of each selection mode into its own method from `PerformSelection` in `SelectionModeHandler`

- Pinta.Gui.Widgets/Widgets/ColorGradientWidget.cs
- Grouped related values (see `p` in `HandleMotionNotifyEvent`)
- Single-expression initialization in `get`ter of `GradientRectangle`
- Re-formatting in `NormalizeY`
- Inverted `if` in `FindValueIndex` (reducing nesting)
> Miscellaneous refactorings in `ColorGradientWidget`

- Pinta.Tools/Editable/Shapes/LineCurveSeriesEngine.cs
and made `Arrow1` and `Arrow2` into properties
> Compacted code in `LineCurveSeriesEngine.GenerateCubicBezierCurvePoints`

- Pinta.Gui.Widgets/Widgets/Ruler.cs
Extracted settings creation form `Ruler.Draw` into its own method
> Extracted settings creation form `Ruler.Draw` into its own method

- Pinta.Tools/Tools/TextTool.cs
> In `TextTool`, split `OnMouseDown` into several, smaller methods

- Pinta.Core/Effects/GradientRenderer.cs
Also, grouped start and end alphas
> Extracted method from `GradientRenderer.Render`

- Pinta.Gui.Widgets/Widgets/PointPickerGraphic.cs
In order to separate calculation from state changes
> Extracted method in `PointPickerGraphic.Draw()`

- Pinta.Gui.Widgets/Widgets/AnglePickerGraphic.cs
To separate calculations from state changes
> Extracted methods in `AnglePickerGraphic`

- Pinta.Core/Classes/AsyncEffectRenderer.cs
- Pinta.Core/Managers/LivePreviewManager.cs
In `LivePreviewManager` and `AsyncEffectRenderer`
> Grouped coordinates in point `struct`s

- Pinta.Core/Classes/DocumentSelection.cs
- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
And added `get`ters, `set`ters, and fixed a naming violation on the way
> Simplified collection initializations

- Directory.Packages.props
- tests/Pinta.Core.Tests/AngleTest.cs
- tests/Pinta.Core.Tests/BitMaskTest.cs
- tests/Pinta.Core.Tests/DashPatternTest.cs
- tests/Pinta.Core.Tests/FileFormatTests.cs
- tests/Pinta.Core.Tests/OtherExtensionsTest.cs
- tests/Pinta.Core.Tests/ScanlineTest.cs
- tests/Pinta.Core.Tests/TextEngineTest.cs
- tests/Pinta.Core.Tests/UtilityTest.cs
- tests/Pinta.Effects.Tests/Utilities.cs
The API changes were automatically applied by the `NUnit.Analyzers` tool.
> Update to NUnit 4.0

- Pinta.Core/Effects/HsvColor.cs
- Pinta.Core/Effects/RgbColor.cs
> In `HsvColor` and `RgbColor`, made the declaration and assignment of a few variables a single statement

- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Editable/Shapes/EllipseEngine.cs
- Pinta/Actions/Edit/PasteAction.cs
- Pinta/Actions/Edit/PasteIntoNewLayerAction.cs
- In `PasteAction.Paste()`
- In `BaseEditEngine.CalculateModifiedCurrentPoint()`
- In `EllipseEngine.CreatePoints()`
> Bundled position parameters/variables

- Pinta.Core/Widgets/ToolBarDropDownButton.cs
They were not being used.
Also, fixed naming violation on the way
> Removed setters in properties of `ToolBarItem`

- Pinta.Core/Actions/ImageActions.cs
- Pinta.Core/Actions/LayerActions.cs
- Pinta.Core/Classes/Document.cs
- Pinta.Core/Classes/DocumentWorkspace.cs
- Pinta.Core/Classes/Layer.cs
- Pinta.Core/Classes/Point.cs
- Pinta.Core/Classes/UserLayer.cs
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Core/Extensions/OtherExtensions.cs
- Pinta.Core/ImageFormats/GdkPixbufFormat.cs
- Pinta.Core/ImageFormats/OraFormat.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta.Effects/Effects/EmbossEffect.cs
- Pinta.Effects/Effects/FragmentEffect.cs
- Pinta.Effects/Effects/GaussianBlurEffect.cs
- Pinta.Effects/Effects/LocalHistogramEffect.cs
- Pinta.Effects/Effects/TileEffect.cs
- Pinta.Effects/Effects/TwistEffect.cs
- Pinta.Effects/Effects/ZoomBlurEffect.cs
- Pinta.Gui.Widgets/Widgets/Layers/LayersListViewItemWidget.cs
- Pinta.Tools/Tools/ColorPickerTool.cs
- Pinta.Tools/Tools/FloodTool.cs
- Pinta.Tools/Tools/PanTool.cs
- Pinta.Tools/Tools/ZoomTool.cs
- Pinta/Actions/Edit/PasteAction.cs
- Pinta/Actions/Edit/PasteIntoNewLayerAction.cs
- Pinta/Dialogs/ResizeCanvasDialog.cs
- Pinta/Dialogs/ResizeImageDialog.cs
- tests/Pinta.Core.Tests/OtherExtensionsTest.cs
- tests/Pinta.Core.Tests/Utilities.cs
It's not bundled all the way through, but it's getting there.
Also I did some things along the way like adding `{ get; set; }` to a property, and a bit of formatting
> Bundled several arguments and variables related to positions and sizes

- Pinta.Core/Actions/ViewActions.cs
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Effects/Effects/BulgeEffect.cs
- Pinta.Tools/Brushes/CircleBrush.cs
Also, in the second commit, I swapped values using tuples in `CairoExtensions`. If this is not desired, feel free to discard that commit
> Used compound assignments when appropriate

- Pinta.Core/Classes/Point.cs
- Pinta.Core/Extensions/OtherExtensions.cs
- Pinta.Tools/Brushes/SquaresBrush.cs
This is a step towards more concise geometric calculations, and helps us assess if the existing methods are adequate for that
> Used point methods in `CreatePolygonSet` and `SquaresBrush`

- Pinta.Effects/Effects/InkSketchEffect.cs
- The `conv` table was converted to `ImmutableArray`s
- Value coercions were simplified through `Math.Min` and `Math.Max`
- Fixed some const naming violations
- Extracted some calculation methods
> Miscellaneous refactorings in `InkSketchEffect`

- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
Among the most remarkable:
- Replaced a few string literals with `nameof`
- Fixed constant naming violations
- Grouped coordinate pairs in several places
> Miscellaneous improvements in `Effects.CurvesDialog.cs`

- Pinta.Core/Classes/DocumentSelection.cs
- Pinta.Core/Effects/ColorDifferenceEffect.cs
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Effects/Effects/FrostedGlassEffect.cs
Along the way removed a few redundant casts and similar
> Better value coercions

- Pinta.Core/Classes/DocumentWorkspace.cs
Like extracting methods, removing redundant casts, etc.
> Miscellaneous refactorings in `DocumentWorkspace.cs`

- Pinta.Effects/Effects/EmbossEffect.cs
- Pinta.Effects/Effects/TileEffect.cs
- Pinta.Effects/Effects/TwistEffect.cs
- Pinta.Effects/Effects/ZoomBlurEffect.cs
On the way I refactored `EmbossEffect` a little
> Removed unnecessary `ref readonly` in several effects

- Pinta.Core/Extensions/CairoExtensions.cs
Mostly for formatting, conciseness, and avoiding repetition
> Miscellaneous refactorings in `CairoExtensions.cs`

- Pinta.Effects/Effects/RadialBlurEffect.cs
> Refactoring in `RadialBlurEffect`

- Pinta.Core/Classes/AsyncEffectRenderer.cs
- Pinta.Core/Classes/DocumentSelection.cs
- Pinta.Core/Classes/Layer.cs
- Pinta.Core/Classes/SurfaceDiff.cs
- Pinta.Core/Effects/ColorBgra.cs
- Pinta.Core/Effects/Histogram.cs
- Pinta.Core/Effects/UnaryPixelOps.cs
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Core/Extensions/GdkExtensions.cs
- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
- Pinta.Effects/Effects/BulgeEffect.cs
- Pinta.Effects/Effects/CloudsEffect.cs
- Pinta.Effects/Effects/FragmentEffect.cs
- Pinta.Effects/Effects/JuliaFractalEffect.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
- Pinta.Effects/Effects/SoftenPortraitEffect.cs
- Pinta.Gui.Addins/AddinListViewItem.cs
- Pinta.Gui.Widgets/Widgets/HistogramWidget.cs
- Pinta.Gui.Widgets/Widgets/Layers/LayersListViewItemWidget.cs
- Pinta.Gui.Widgets/Widgets/PointPickerGraphic.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Editable/Shapes/LineCurveSeriesEngine.cs
- Pinta/Dialogs/NewImageDialog.cs
- Pinta/MacInterop/CoreFoundation.cs
- Pinta/MainWindow.cs
On the way (in separate commits) made small improvements in several places.
> Removing more redundant casts

- Pinta.Effects/Effects/RadialBlurEffect.cs
Extracted a method, got rid of local function, and replaced the method `Rotate` with `Rotated`
> Refactorings in `RadialBlurEffect`

- Pinta.Core/Effects/Utility.cs
And making the `Swap` method generic
> Reformatting `Utility`

- Pinta.Core/Classes/Re-editable/Text/TextLayout.cs
- Pinta.Effects/Effects/CloudsEffect.cs
- Pinta.Gui.Widgets/Widgets/Canvas/CanvasRenderer.cs
- Pinta.Gui.Widgets/Widgets/StatusBarColorPaletteWidget.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Editable/Shapes/RoundedLineEngine.cs
- Pinta/MacInterop/Carbon.cs
In the last commit I also inverted a few `if` blocks, along with some more local refactorings in `BaseEditEngine`
> Unassigned local variables were removed / converted to discards

- Pinta.Core/Classes/Palette.cs
Extracted method in `LoadColors` (admittedly, it could be better)
Also, reformatted in several places of the same file
> Small-scale refactorings in `Palette`

- Pinta.Core/Actions/EditActions.cs
- Pinta.Core/Actions/FileActions.cs
- Pinta.Core/Classes/DocumentHistory.cs
- Pinta.Core/Effects/GradientRenderers.cs
- Pinta.Core/Effects/UnaryPixelOps.cs
- Pinta.Core/Extensions/GdkExtensions.cs
- Pinta.Core/Extensions/GioStream.cs
- Pinta.Core/ImageFormats/OraFormat.cs
- Pinta.Core/Widgets/ToolBarDropDownButton.cs
- Pinta.Tools/Tools/EraserTool.cs
- Pinta.Tools/Tools/PaintBucketTool.cs
- Pinta.Tools/Tools/PencilTool.cs
Also, some `switch` statements were converted to expressions
Some small-scale reformatting and refactoring were done along the way
> Converted a few series of `if`s to pattern matching

- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
- A bit more generative
- Reduced the scope of a `Random` field (now it's a variable). Should be good enough as its initial seed comes from the system clock
- A bit of reformatting
> Local refactorings in `SimpleEffectDialog`

- Pinta.Core/Managers/ToolManager.cs
- Pinta.Gui.Addins/InstallDialog.cs
> Comparing `Count` to 0 instead of using `Any()`

- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
I think this is less performant than the previous one, but it could help in refactoring
> Using LINQ methods in order to extract configuration values in `SimpleEffectDialog`

- Pinta.Gui.Widgets/Dialogs/MemberReflector.cs
- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
And I like the idea of this evolving into a neat, type-safe reflection library that makes things easier and that we can test :)
> Extracted reflection code from `SimpleEffectDialog` into its own class

- Pinta.Core/Classes/Rectangle.cs
- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
Mostly `if` inversion. A new constant field `RectangleD.Zero` was added to simplify things
> Refactoring in `CurvesDialog` and `BaseEditEngine`

- Pinta.Gui.Addins/AddinManagerDialog.cs
It became patent that some fields are used as locals, so I was able to remove them
> Refactored out creation of controls in `AddinManagerDialog` into its own methods

- Pinta.Gui.Widgets/Widgets/History/HistoryItemWidget.cs
I don't know how this escaped me the first time, but here it is, and also I re-arranged some code lines on the way, for clarity
> Sealed classes in `HistoryItemWidget`

- Pinta.Gui.Widgets/Widgets/Ruler.cs
I also want to refactor the Cairo part, but I need to get a bit more familiar with the intent behind each part and with how Cairo manages its internal state.
When it's refactored right, creating tests for the visual output of this (so that we can test that the ruler is being drawn correctly) should be possible :)
> Refactored `Ruler` to minimize variable reassignment

- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
There's a section that is pending, and that has been left for a future pull request; specifically, code that depends on state changes, which I can't confidently modify yet unless I know exactly what happens in GTK. This section is under the `TODO:` comment
> Partially refactored control creation in `LevelsDialog` for clarity

- Pinta.Gui.Addins/InstallDialog.cs
Now the code is just working with the controls as variables, and at the end of the constructor block, it's explicit about the references to be kept
> Refactored control creation in `InstallDialog`

- Pinta.Docking/DockItem.cs
- Pinta/Pads/CanvasPad.cs
- Pinta/Pads/HistoryPad.cs
- Pinta/Pads/LayersPad.cs
This is not just a composite control, but it involves side effects, so the code may not be as nice at the other ones, but I tried to contain the ugliness to the part under the comment `// --- Initialization`
> Refactored constructor in `DockItem` for greater clarity

- Pinta.Gui.Widgets/Dialogs/SimpleEffectDialog.cs
I think this is about as far as we can get without creating some other utility classes. I will think of some way to abstract it better
> Reformatting and small refactorings of `SimpleEffectDialog`

- Pinta.Effects/Effects/VignetteEffect.cs
Some of the translations that have been submitted are strange, so I think that the meaning of 'vignette' should be explained
> Added comment for accurate translation of the text `"Vignette"`

- CHANGELOG.md
- Pinta.Core/ImageFormats/FormatDescriptor.cs
- Pinta.Core/Managers/ImageConverterManager.cs
- Pinta/Actions/File/SaveDocumentImplementationAction.cs
This fixes #909
Note that this is my first time using C# and GTK, so the code quality might be subpar.  
Don't hesitate to point me in the right direction and ask for changes.
> Warn when exporting to a flat format

- Pinta.Effects/Effects/FeatherEffect.cs
Along with a few minor things such as using explicit variable types and removing certain intermediate variables (those which correspond to properties that we can just read from `roi`)
> Decreased nesting in `FeatherEffect`

- Pinta.Effects/Effects/AlignObjectEffect.cs
Mostly for conciseness and to avoid variable reassignment
> Refactored `AlignObjectEffect`

- Pinta.Core/Managers/ImageConverterManager.cs
- Pinta.Core/Managers/WorkspaceManager.cs
Along with a bit more syntactic sugar
> Reformatting of `WorkspaceManager` and `ImageConverterManager`

- Pinta.Gui.Widgets/Widgets/Canvas/CanvasWindow.cs
- Pinta/MainWindow.cs
- Pinta/WindowShell.cs
Small refactorings done on files that were touched
> Removed references to `PintaCore` from `WindowShell` and `CanvasWindow`

- Pinta.Effects/Effects/FeatherEffect.cs
- Pinta.Effects/Effects/PixelateEffect.cs
Removed unnecessary access to `Bgra` in `ColorBgra` and unnecessary variable re-assignment
> Simplified code in `FeatherEffect` and `PixelateEffect`

- Pinta.Core/Classes/AsyncEffectRenderer.cs
- Pinta.Core/Managers/LivePreviewManager.cs
> Removed `cancel_render_flag` from `AsyncEffectRenderer`

- Pinta.Core/Effects/GradientRenderer.cs
Among them:
- Minimized variable re-assignment
- Moved constructor to the top of the file, for clarity
- Used auto property accessors wherever there are no checks
> Miscellaneous refactorings in `GradientRenderer`

- Pinta.Effects/Dialogs/Effects.AlignmentDialog.cs
> Refactored control creation in `AlignmentDialog`

- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
The names of the commits describe the changes
> Miscellaneous refactorings in `CurvesDialog`

- Pinta.Effects/Effects/TileEffect.cs
Also, explanations have been added to `GetFinalPixelColor` so that the code is less esoteric and more readable
> Improved naming and reduced re-assignment inside `TileEffect`

- Pinta.Core/Effects/Histogram.cs
To make it easier to see what's happening
> Organized calculations inside `Histogram`

- Pinta.Core/ImageFormats/OraFormat.cs
It was in confusing blocks that could be confusing to read, because that was the only way to avoid variable names clashing. I renamed them and now statements can all be written normally, one after another
> Reformatted code in `OraFormat`

- Pinta.Core/Classes/Palette.cs
It used to be that a tuple (bundling the retrieved colors and the errors, if any) was returned. However, only one of them is ever used, so now the method works more conventionally, by throwing an exception.
> Simplified signature of `LoadColors`

- Pinta.Tools/Editable/Shapes/RoundedLineEngine.cs
Among the most important changes:
- Reduced scope of several variables
- `GenerateQuadraticBezierCurvePoints` is now a generator
> Refactored `RoundedLineEngine`

- Pinta.Tools/Editable/Shapes/EllipseEngine.cs
Reduced the scope of certain variables and `sealed` the class
> Refactored `EllipseEngine`

- Pinta.Core/Extensions/OtherExtensions.cs
Perhaps the most important one is removing an unused method
> Miscellaneous refactorings in `OtherExtensions`

- Pinta.Core/Actions/WindowActions.cs
- Pinta.Core/Classes/Layer.cs
- Pinta.Core/Extensions/CairoExtensions.cs
- Pinta.Core/Managers/LivePreviewManager.cs
- Pinta.Gui.Widgets/Widgets/Canvas/CanvasRenderer.cs
- Pinta/ActionHandlers.cs
- `WindowActions.RemoveDocument`
- `CairoExtensions.SetSourceSurface`
- `LivePreviewManager.HandleUpdate`
> Removed unused parameters in methods in `Pinta.Core`

- Pinta.Core/Actions/LayerActions.cs
Along with minor, local refactorings throughout the file
> Organized menu creation in `LayerActions`

- Pinta.Core/Classes/AsyncEffectRenderer.cs
- Pinta.Core/Managers/LivePreviewManager.cs
This refactoring path should (eventually) allow us to get rid of `restart_render_flag` and other similarly awkward control mechanisms. Some of the awkwardness with the code comes from things having too broad of a scope, and this is a step towards fixing that.
> Sealed `AsyncEffectRenderer` and turned its `virtual` methods into `event`s

- Pinta.Core/Effects/ColorDifferenceEffect.cs
- Pinta.Effects/Effects/EdgeDetectEffect.cs
- Pinta.Effects/Effects/ReliefEffect.cs
These refactorings are described by the commits' messages.
I plan to flatten them as I did with the descendants of `WarpEffect`, but this one seems to be a bit more involved, so I'll do it in a future pull request.
> Miscellaneous refactorings in `ColorDifferenceEffect`

- Pinta.Effects/Effects/BulgeEffect.cs
At first I just wanted to adjust the calculations so that they are performed based on the selection (it has a similar problem to what `TwistEffect` used to have, as was discussed in #1089), however, this could be a little bit involved, because `BulgeEffect` has an extra offset property, so there's more to think about. It's better to leave this for a future pull request.
> Extracted method for computing pixel color in `BulgeEffect`

- Pinta.Core/Algorithms/HistogramRGB.cs
- Pinta.Core/Algorithms/Mathematics.cs
- Pinta.Core/Effects/Utility.cs
- Pinta.Effects/Algorithms/PerlinNoise.cs
- Pinta.Effects/Classes/ColorGradient.cs
- Pinta.Effects/Effects/BulgeEffect.cs
- Pinta.Effects/Effects/GradientHelper.cs
- Pinta.Effects/Effects/MandelbrotFractalEffect.cs
- Pinta.Effects/Effects/PolarInversionEffect.cs
- Pinta.Gui.Widgets/Widgets/HistogramWidget.cs
The implementations of these functions are extremely simple, even 'canonical'. Furthermore I made all of them except for `Lerp` so I don't think the license headers are needed.
> Moved several mathematical functions from `Utility` to `Mathematics`, and genereralized them

- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
Mostly bundling things semantically and reducing re-assignment
> Miscellaneous refactorings in `Effects.CurvesDialog.cs`

- Pinta.Core/Actions/EditActions.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.Dialog.cs
Achieving this required creating an extension method for `Gtk.NativeDialog`
> Handler in `EditActions` was made asynchronous

- Pinta/Dialogs/ProgressDialog.cs
I plan to make it asynchronous after the refactoring of the renderer is done, and this refactoring should make it a bit more straightforward.
> Organized initialization of `ProgressDialog`

- Pinta.Core/Actions/LayerActions.cs
- Pinta.Gui.Addins/AddinManagerDialog.cs
I would like to use `Gtk.FileDialog`, but see #1136. Furthermore, the `InstallDialog` in a certain method that I touched wasn't made asynchronous. That one requires some re-structuring.
> More file dialogs were made asynchronous

- Pinta.Core/Extensions/GdkExtensions.cs
Including reduction of variable re-assignment and re-formatting
> Miscellaneous refactorings in `GdkExtensions`

- Pinta.Core/Actions/LayerActions.cs
- Pinta.Gui.Addins/AddinManagerDialog.cs
> Migrated open file dialogs in `LayerActions` and `AddinManagerDialog` to `FileDialog`

- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
As usual, aimed at improving type safety and reducing variable re-assignment
> Miscellaneous refactorings in `BaseEditEngine`

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
Nothing too fancy for now. Just formatting, fixing naming violations, modernizing some syntax, adding `readonly` modifiers, and other similar stuff.
> Miscellaneous refactorings in `ColorPickerDialog`

- Pinta.Tools/Handles/MoveHandle.cs
- Pinta.Tools/Tools/EllipseSelectTool.cs
- Pinta.Tools/Tools/EllipseTool.cs
- Pinta.Tools/Tools/LineCurveTool.cs
- Pinta.Tools/Tools/RectangleSelectTool.cs
- Pinta.Tools/Tools/RectangleTool.cs
- Pinta.Tools/Tools/RoundedRectangleTool.cs
- Pinta.Tools/Tools/SelectTool.cs
- Pinta.Tools/Tools/TextTool.cs
This might cause bug https://bugs.launchpad.net/pinta/+bug/2072309 to be harder to reproduce, so I'm holding off on merging this for now
Fixes: #918
> Cache cursors for tools which change the cursor based on mouse events

- .github/workflows/build.yml
- CHANGELOG.md
- installer/macos/build_installer.sh
- installer/macos/bundle_gtk.py
- readme.md
> CI: add an arm64 macOS installer

- Pinta.Core/Algorithms/Utility.cs
- installer/addins/Program.cs
- tests/Pinta.Core.Tests/BitMaskTest.cs
- tests/Pinta.Core.Tests/FileFormatTests.cs
- tests/Pinta.Core.Tests/OtherExtensionsTest.cs
- tests/Pinta.Core.Tests/ScanlineTest.cs
- tests/Pinta.Core.Tests/TextEngineTest.cs
- tests/Pinta.Effects.Tests/AdjustmentsTest.cs
- tests/PintaBenchmarks/AdjustmentsBenchmarks.cs
- tests/PintaBenchmarks/CanvasRendererBenchmarks.cs
- tests/PintaBenchmarks/EffectsBenchmarks.cs
At first, I realized that some collection initializations had escaped me, so I modernized them but also tidied up the files touched
> Syntax modernization and formatting at several places

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
Also, nested configuration classes were made immutable
> Organized control creation in `ColorPickerSlider`

- Pinta.Core/HistoryItems/TextHistoryItem.cs
- Pinta.Tools/Tools/TextTool.cs
With some small-scale refactorings along the way
> Removed `PintaCore` references from `TextHistoryItem`

- Directory.Packages.props
- Pinta.Core/Extensions/GdkExtensions.cs
- Pinta.Core/Extensions/GdkPixbufExtensions.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.Dialog.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.Widget.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.cs
- Pinta.Core/Extensions/PangoExtensions.cs
- Pinta.Gui.Addins/AddinListViewItem.cs
- Pinta.Gui.Addins/Pinta.Gui.Addins.csproj
- Pinta.Gui.Widgets/Pinta.Gui.Widgets.csproj
- Pinta.Gui.Widgets/Widgets/History/HistoryItemWidget.cs
- Pinta.Gui.Widgets/Widgets/Layers/LayersListViewItemWidget.cs
- tests/PintaBenchmarks/PintaBenchmarks.csproj
- Use the new GObject source generator for GObject subclasses
- Minor internal API changes
> Upgrade to gir.core 0.6.2

- Pinta.Core/Effects/BaseEffect.cs
- Pinta.Core/Extensions/AddinUtilities.cs
> Moved `AddinLocalizerWrapper` to `Pinta.Core`

- po/nl.po
expands the translations for Dutch
> i18n(nl) update Dutch translation

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
`swatch_recent`, `swatch_palette`, and `original_colors`
With some formatting on the way
> Made a few fields into locals in `ColorPickerDialog`

- Pinta.Core/Extensions/Gtk/GtkExtensions.Widget.cs
- Pinta.Core/Extensions/ToolBoxButton.cs
- Pinta.Resources/Pinta.Resources.csproj
- Pinta.Resources/ResourceManager.cs
- Pinta.Resources/Resources/style.css
- Pinta.Resources/Styles.cs
- Pinta/MainWindow.cs
> Add and use css styles

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
See second commit.
The issue was first mentioned in https://github.com/PintaProject/Pinta/pull/1382#issuecomment-2826279772
> Fixes #1390

- Pinta.Tools/Tools/TextTool.cs
> When drawing a text with outline, draws fill after stroke and not before

- Pinta.Core/Actions/AddinActions.cs
- Pinta.Core/Actions/AppActions.cs
- Pinta.Core/Actions/Command.cs
- Pinta.Core/Actions/EditActions.cs
- Pinta.Core/Actions/FileActions.cs
- Pinta.Core/Actions/HelpActions.cs
- Pinta.Core/Actions/ImageActions.cs
- Pinta.Core/Actions/LayerActions.cs
- Pinta.Core/Actions/ViewActions.cs
- Pinta.Core/Actions/WindowActions.cs
- Pinta.Core/Extensions/Gtk/GtkExtensions.Application.cs
- Pinta.Core/Managers/EffectsManager.cs
An important step for realizing #1408 
~There is an important catch: the File > Quit menu item appears disabled, and I don't know why that is yet.~ This has since been fixed
> Keyboard shortcuts are now stored in `Command` objects

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
There's still a lot to do, but changes are piling up
> Partly organized control creation in `ColorPickerDialog`

- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Editable/Shapes/OrganizedPointCollection.cs
- Pinta.Tools/Editable/Shapes/ShapeEngineCollection.cs
- Pinta.Tools/HistoryItems/ShapesHistoryItem.cs
- Pinta.Tools/HistoryItems/ShapesModifyHistoryItem.cs
(As opposed to a separate collection class)
> `ShapeEngineCollection` is now a set of utility methods

- Pinta.Resources/icons/pinta-icons.md
> Added dithering icon to `pinta-icons.md`

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
Mainly, more things were moved out of the constructor, and to the bottom of the constructor
> Miscellaneous reformattings in `ColorPickerDialog`

- Pinta.Gui.Widgets/Widgets/HScaleSpinButtonWidget.cs
Organization of control creation, and stylistic changes
> Refactorings in `HScaleSpinButtonWidget`

- Pinta.Core/Actions/LayerActions.cs
- Pinta.Core/ImageFormats/FormatDescriptor.cs
- Pinta.Core/Managers/ImageConverterManager.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta/Actions/File/OpenDocumentAction.cs
- Pinta/Actions/File/SaveDocumentImplementationAction.cs
I think `IsExportAvailable` is clearer than `IsReadOnly`, and `IsImportAvailable` is clearer than `IsWriteOnly`
> Changed informative methods in `FormatDescriptor`

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
Most notably, I removed the awkward mechanism `Func<,> colorSelectors` mechanism
> Simplified creation of color display in `ColorPickerDialog`

- Pinta.Gui.Widgets/Widgets/Layers/LayersListViewItemWidget.cs
https://github.com/user-attachments/assets/117365b7-fbe9-4fd0-93ad-7846284623a7
> Menu of layer operations that appears when right-clicking item in layers list

- Pinta/MainWindow.cs
22ae53228b2876c32340abe5cd45a3064433baf2 is unrelated but could be a nice modernization
> `IdleAdd` instead of creating timer in `MainWindow`

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
With the aim of having a single source of truth
> Refactoring of certain values from `ColorPickerDialog` into constants

- .github/workflows/build.yml
- CHANGELOG.md
- Directory.Build.props
- Pinta.Core/Actions/WindowActions.cs
- Pinta.Core/Managers/ActionManager.cs
- Pinta.Core/Managers/ToolManager.cs
- Pinta.Core/Managers/WorkspaceManager.cs
- Pinta.Core/PintaCore.cs
- Pinta.Effects/Dialogs/Effects.LevelsDialog.cs
- Pinta.Gui.Widgets/Widgets/Canvas/PintaCanvas.cs
- Pinta/Actions/Edit/PasteIntoNewImageAction.cs
- Pinta/Actions/File/CloseDocumentAction.cs
- Pinta/Actions/File/NewDocumentAction.cs
- Pinta/Actions/Window/SaveAllDocumentsAction.cs
- Pinta/AddinSetupService.cs
- Pinta/Main.cs
- Pinta/MainWindow.cs
- configure.ac
- installer/macos/Info.plist
- installer/windows/bundle_gtk.targets
- installer/windows/installer.iss
- po/ja.po
- po/lv.po
- po/ru.po
- po/ta.po
- xdg/pinta.appdata.xml.in
> Backport bug fixes for 3.0.2

- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
Along with some minor refactorings along the way
> `ColorPickerDialog`: relying on default values inside constructor

- Pinta.Effects/Algorithms/Warp.cs
- Pinta.Effects/Effects/DentsEffect.cs
- Pinta.Effects/Effects/PolarInversionEffect.cs
Upon looking at it, it just seems to represent an offset
> Replacing instances of `Warp.TransformData` with `PointD`

- Pinta.Effects/Effects/TwistEffect.cs
Also, the color blending is now delegated to the appropriate method, and this could be a model for how this pattern (repeated in so many places) could be refactored away to reduce code repetition.
> Refactoring of `TwistEffect` to use `PointF` operations

- Pinta.Gui.Widgets/Widgets/Layers/LayersListView.cs
When a history item is added, the list view is rebuilt and the selection is reset back to its original value. When this happens, we don't need to trigger another change to the document's active layer since the selection won't be any different. This previously led to an infinite loop because the current tool is committed before updating the document's active layer.
Fixes: #1463
> Add a flag to prevent infinite loop if changing layers adds a history item

- Pinta.Core/Algorithms/Utility.cs
- Pinta.Effects/Effects/VignetteEffect.cs
I think now it's easier to see what's happening, and repetition is reduced, too
> Organized calculations in `VignetteEffect`

- Directory.Packages.props
- Pinta.Core/Extensions/Gtk/GtkExtensions.Interaction.cs
- Pinta.Gui.Addins/AddinListView.cs
- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
- Pinta.Gui.Widgets/Widgets/ColorPickerSlider.cs
- Pinta.Gui.Widgets/Widgets/History/HistoryListView.cs
- Pinta.Gui.Widgets/Widgets/Layers/LayersListView.cs
- Pinta/Dialogs/LayerPropertiesDialog.cs
- Pinta/Dialogs/NewImageDialog.cs
This adds support for interface signals, so some old workarounds can be removed
> Update gir.core to 0.7.0-preview.2

- tests/PintaBenchmarks/BlendOpsBenchmarks.cs
These can be run with a command such as `dotnet run --project tests/PintaBenchmarks -c Release -- -f \*NormalBlendOp`
> Add benchmarks for the blend ops

- Pinta.Core/Algorithms/Utility.cs
- Pinta.Core/Effects/GradientRenderers.cs
- Pinta.Effects/Effects/TwistEffect.cs
- Pinta.Gui.Widgets/Widgets/ColorPickerDialog.cs
- Pinta.Tools/Editable/Shapes/ShapeEngineCollection.cs
Knowing that taking the square root is an expensive operation, I try to reduce its usage if possible
> Optimized distance calculation operations in several places

- Pinta.Core/Effects/GradientRenderers.cs
- Pinta.Effects/Dialogs/Effects.CurvesDialog.cs
- Pinta.Tools/Editable/EditEngines/BaseEditEngine.cs
- Pinta.Tools/Editable/Shapes/OrganizedPointCollection.cs
- Pinta.Tools/Handles/RectangleHandle.cs
- Pinta.Tools/Tools/EraserTool.cs
- Pinta.Tools/Tools/ZoomTool.cs
Sometimes the distance is being compared to thresholds of 0 or 1, which are the same when the distance is squared. So those ones are straightforward :)
Most purely stylistic changes are in their own request.
> Optimized more distance calculations

- Pinta.Effects/Effects/DentsEffect.cs
- Pinta.Effects/Effects/PolarInversionEffect.cs
> Ensure all effect parameters have translatable labels

- Pinta.Core/Classes/SurfaceDiff.cs
- tests/Pinta.Core.Tests/SurfaceDifferenceTests.cs
> Refactored `SurfaceDiff.Create` to use nullable `RectangleI`

- Pinta.Core/Classes/SurfaceDiff.cs
Also, I think that in the future we could get rid of those timers and debug statements in the `#if DEBUG_DIFF` blocks and creating benchmarks instead.
> Extracted methods in `SurfaceDiff.Create`

- Pinta.Core/Classes/Angle.cs
- tests/Pinta.Core.Tests/AngleTest.cs
- Constructors now check that number is valid
- Implemented `IEquatable<T>`
> Enhanced angle types

- Pinta.Core/Messages/ActionData.cs
- Pinta/Actions/Edit/OffsetSelectionAction.cs
- Pinta/Actions/Edit/ResizePaletteAction.cs
- Pinta/Actions/Image/ResizeCanvasAction.cs
- Pinta/Actions/Image/ResizeImageAction.cs
- Pinta/Actions/Layers/LayerPropertiesAction.cs
- Pinta/Dialogs/OffsetSelectionDialog.cs
- Pinta/Dialogs/ResizeCanvasDialog.cs
- Pinta/Dialogs/ResizeImageDialog.cs
- Pinta/Messages/ActionOptions.cs
Making sure that the dialogs are being properly destroyed, and also separating the logic of the graphical dialog from the logic of the response.
> Refactored dialog creation in several actions

- Pinta.Core/Algorithms/Utility.cs
- Pinta.Core/Extensions/Cairo/CairoExtensions.Samples.cs
`float.IsFinite` does basically the same thing
> Removed `Utility.IsNumber`

- Pinta.Effects/Effects/ReduceNoiseEffect.cs
By inlining a method and moving repetition to its own method
> Made `ReduceNoiseEffect` more concise
